const test=require('node:test');
const assert=require('node:assert/strict');
const {DatabaseSync}=require('node:sqlite');
function Database(){const db=new DatabaseSync(':memory:');db.transaction=fn=>(...args)=>{db.exec('BEGIN IMMEDIATE');try{const r=fn(...args);db.exec('COMMIT');return r;}catch(e){db.exec('ROLLBACK');throw e;}};return db;}
const {createPricing}=require('./pricing');
const {createDigiflazz,md5}=require('./digiflazz');
function setup(responses=[]){
  const db=Database();db.exec("CREATE TABLE users(discord_id TEXT PRIMARY KEY,balance INTEGER NOT NULL DEFAULT 0);INSERT INTO users VALUES('12345678901234567',100000);");
  const pricing=createPricing(db);pricing.set('10','1000');
  const calls=[];const fetchImpl=async(url,opt)=>{calls.push({url,body:JSON.parse(opt.body)});const body=responses.shift();return {ok:true,status:200,text:async()=>JSON.stringify(body)};};
  const env={DIGIFLAZZ_USERNAME:'buyer',DIGIFLAZZ_API_KEY:'secret',DIGIFLAZZ_WEBHOOK_SECRET:'hook',DIGIFLAZZ_TESTING:'true',DIGIFLAZZ_CATEGORY:'Games'};
  const model=createDigiflazz({db,pricing,env,fetchImpl,now:(()=>{let n=100000;return()=>++n;})()});return {db,model,calls};
}
const product={product_name:'Mobile Legends 86 Diamonds',category:'Games',brand:'MOBILE LEGENDS',type:'Umum',price:20000,buyer_sku_code:'ml86',buyer_product_status:true,seller_product_status:true,unlimited_stock:true,stock:0,multi:true,desc:'86 Diamonds'};
test('sync menyimpan katalog dan signature price list benar',async()=>{const {model,calls}=setup([{data:[product]}]);assert.equal(await model.sync(),1);assert.equal(model.brands()[0].brand,'MOBILE LEGENDS');assert.equal(model.products('MOBILE LEGENDS')[0].selling_price,23000);assert.equal(calls[0].body.sign,md5('buyer'+'secret'+'pricelist'));});
test('transaksi sukses memotong saldo sekali',async()=>{const {db,model}=setup([{data:[product]},{data:{ref_id:'placeholder'}}]);await model.sync();const q=model.quote('12345678901234567',model.products('MOBILE LEGENDS')[0].id,'12345');
  // Override fetch through a second model is unnecessary; mutate queued response with ref generated by observing request via custom setup below.
  let transactionBody;const env={DIGIFLAZZ_USERNAME:'buyer',DIGIFLAZZ_API_KEY:'secret',DIGIFLAZZ_WEBHOOK_SECRET:'hook',DIGIFLAZZ_TESTING:'true',DIGIFLAZZ_CATEGORY:'Games'};
  const pricing=createPricing(db);const m=createDigiflazz({db,pricing,env,fetchImpl:async(url,opt)=>{transactionBody=JSON.parse(opt.body);return {ok:true,status:200,text:async()=>JSON.stringify({data:{ref_id:transactionBody.ref_id,customer_no:transactionBody.customer_no,buyer_sku_code:transactionBody.buyer_sku_code,status:'Sukses',rc:'00',message:'Transaksi Sukses',price:20000,sn:'SN123'}})};}});
  const q2=m.quote('12345678901234567',m.products('MOBILE LEGENDS')[0].id,'12345');const o=await m.buy('12345678901234567',q2.token);assert.equal(o.status,'success');assert.equal(o.sn,'SN123');assert.equal(db.prepare('SELECT balance FROM users WHERE discord_id=?').get('12345678901234567').balance,77000);
});
test('status gagal mengembalikan saldo otomatis hanya sekali',async()=>{const {db,model}=setup([{data:[product]}]);await model.sync();let body;const original=global.fetch; // model already owns fetchImpl from setup; create fresh model sharing db
  const pricing=createPricing(db);const env={DIGIFLAZZ_USERNAME:'buyer',DIGIFLAZZ_API_KEY:'secret',DIGIFLAZZ_WEBHOOK_SECRET:'hook',DIGIFLAZZ_TESTING:'true',DIGIFLAZZ_CATEGORY:'Games'};
  const m=createDigiflazz({db,pricing,env,fetchImpl:async(url,opt)=>{body=JSON.parse(opt.body);return {ok:true,status:200,text:async()=>JSON.stringify({data:{ref_id:body.ref_id,customer_no:body.customer_no,buyer_sku_code:body.buyer_sku_code,status:'Gagal',rc:'14',message:'Tujuan salah',price:20000}})};}});
  const p=m.products('MOBILE LEGENDS')[0],q=m.quote('12345678901234567',p.id,'bad');const o=await m.buy('12345678901234567',q.token);assert.equal(o.status,'failed');assert.equal(o.refunded,1);assert.equal(db.prepare('SELECT balance FROM users WHERE discord_id=?').get('12345678901234567').balance,100000);m.apply(o.ref_id,{ref_id:o.ref_id,customer_no:o.customer_no,buyer_sku_code:o.sku,status:'Gagal',price:20000});assert.equal(db.prepare('SELECT balance FROM users WHERE discord_id=?').get('12345678901234567').balance,100000);void original;
});
test('webhook signature tervalidasi',()=>{const {model}=setup();const raw=Buffer.from('{"data":{"ref_id":"x"}}');const crypto=require('node:crypto');const sig='sha1='+crypto.createHmac('sha1','hook').update(raw).digest('hex');assert.equal(model.hmacValid(raw,sig),true);assert.equal(model.hmacValid(raw,'sha1=deadbeef'),false);});
