const {test}=require('node:test'),assert=require('node:assert/strict'),{DatabaseSync}=require('node:sqlite');
const {createEfficiency,createEfficiencyHandler,validateAttachment}=require('./efficiency');
const buyer='522774531815768081',other='522774531815768082',admin='522774531815768083';
function setup(){const sql=new DatabaseSync(':memory:');sql.exec(`CREATE TABLE orders(id INTEGER PRIMARY KEY,discord_id TEXT,provider_order_id TEXT,status TEXT,otp TEXT,refunded INTEGER DEFAULT 0,phone TEXT,product_name TEXT,amount INTEGER);
CREATE TABLE manual_topup_requests(status TEXT);CREATE TABLE direct_purchases(state TEXT);CREATE TABLE topups(gateway TEXT,credited INTEGER,status TEXT);`);
const db={exec:s=>sql.exec(s),prepare:s=>sql.prepare(s),transaction:fn=>(...args)=>{sql.exec('BEGIN IMMEDIATE');try{const r=fn(...args);sql.exec('COMMIT');return r;}catch(e){sql.exec('ROLLBACK');throw e;}}};let isAdmin=true;const staff={isAdmin:id=>id===admin && isAdmin};return {sql,db,staff,model:createEfficiency({db,staff}),revoke:()=>isAdmin=false};}
const quote={platformId:1,countryId:7,operatorId:433,name:'WhatsApp USA'};
test('favorites persist, deduplicate tuple, keep carrier, enforce ownership and cap at 20',()=>{const t=setup(),f=t.model.save(buyer,quote);assert.equal(f.operator,'433');assert.equal(t.model.save(buyer,quote).id,f.id);assert.equal(createEfficiency(t).favorite(buyer,f.id).app,'1');assert.throws(()=>t.model.favorite(other,f.id));assert.throws(()=>t.model.remove(other,f.id));for(let n=2;n<=20;n++)t.model.save(buyer,{...quote,countryId:n+10});assert.throws(()=>t.model.save(buyer,{...quote,countryId:99}),/20/);assert.equal(t.model.favorites(buyer,99).page,3);t.model.remove(buyer,f.id);assert.equal(t.model.favorites(buyer).count,19);});
test('active orders prioritize waiting OTP, exclude terminal/refunded, paginate and isolate buyers',()=>{const t=setup();const put=t.sql.prepare('INSERT INTO orders(id,discord_id,status,otp,refunded) VALUES(?,?,?,?,?)');put.run(1,buyer,'ACTIVE',null,0);put.run(2,buyer,'OTP_RECEIVED','123',0);put.run(3,buyer,'COMPLETED','123',0);put.run(4,buyer,'CANCELED',null,0);put.run(5,buyer,'ACTIVE',null,1);put.run(6,other,'ACTIVE',null,0);assert.deepEqual(t.model.activeOrders(buyer).rows.map(o=>o.id),[1,2]);assert.throws(()=>t.model.order(buyer,6));for(let n=7;n<13;n++)put.run(n,buyer,'ACTIVE',null,0);assert.equal(t.model.activeOrders(buyer).pages,2);assert.equal(t.model.activeOrders(buyer,999).page,1);});
test('admin summary counts actionable cases and rejects revoked admins',()=>{const t=setup();t.sql.exec("INSERT INTO manual_topup_requests VALUES('pending'),('approved');INSERT INTO direct_purchases VALUES('review'),('resolving'),('fulfilled');INSERT INTO topups VALUES('tripay',0,'creating'),('tripay',0,'pending'),('tripay',1,'settlement'),('midtrans',0,'pending');");assert.deepEqual(t.model.summary(admin),{manual:1,review:2,invoices:3,processing:0,delivery:0,lowStock:0});assert.throws(()=>t.model.summary(buyer));t.revoke();assert.throws(()=>t.model.summary(admin));});
test('attachment validation rejects nonimages, external URLs and oversized uploads',()=>{const a={url:'https://cdn.discordapp.com/attachments/123/456/proof.png?ex=1',contentType:'image/png',size:1024};assert.equal(validateAttachment(a),a.url);for(const v of [{...a,contentType:'application/pdf'},{...a,size:9*1024*1024},{...a,url:'https://example.com/proof.png'},null])assert.throws(()=>validateAttachment(v));});
class Builder{constructor(){this.components=[];}setCustomId(v){this.customId=v;return this;}setLabel(v){this.label=v;return this;}setStyle(){return this;}setDisabled(v){this.disabled=v;return this;}setColor(){return this;}setTitle(){return this;}setDescription(v){this.description=v;return this;}setFooter(){return this;}setImage(){return this;}addComponents(...v){this.components.push(...v);return this;}}
const discord={ActionRowBuilder:Builder,ButtonBuilder:Builder,EmbedBuilder:Builder,ButtonStyle:{Secondary:2}};
test('direct image slash submits existing approval flow privately without credit and admin summary denies before IO',async()=>{const t=setup();let received,response,polls=0,calls=0;const handler=createEfficiencyHandler({discord,model:t.model,staff:t.staff,features:{submit:r=>{received=r;return r;},poll:async()=>polls++},smscode:async()=>calls++});const i={id:'100000000000000001',user:{id:buyer},commandName:'bukti',isChatInputCommand:()=>true,deferReply:async p=>assert.equal(p.ephemeral,true),editReply:async p=>response=p,options:{getAttachment:()=>({url:'https://cdn.discordapp.com/attachments/123/456/proof.jpg',size:1024,contentType:'image/jpeg'}),getInteger:()=>5000,getString:()=>null}};assert.equal(await handler(i),true);assert.equal(received.proof,'https://cdn.discordapp.com/attachments/123/456/proof.jpg');assert.equal(received.amount,5000);assert.match(response.content,/memeriksa/);assert.equal(polls,1);await handler({customId:'admin_eff_summary',user:{id:buyer},reply:async p=>response=p});assert.equal(response.ephemeral,true);assert.match(response.content,/ditolak/);assert.equal(calls,0);});
test('empty, single-page and boundary lists always render unique button IDs, including disabled pagination',async()=>{
  const t=setup(),handler=createEfficiencyHandler({discord,model:t.model,staff:t.staff});let response;
  const i={customId:'favorites',user:{id:buyer},deferReply:async()=>{},editReply:async p=>response=p};
  const check=()=>{const buttons=response.components.flatMap(r=>r.components),ids=buttons.map(b=>b.customId);assert.equal(new Set(ids).size,ids.length);assert.ok(buttons.find(b=>b.label==='Sebelumnya'));assert.ok(buttons.find(b=>b.label==='Berikutnya'));};
  await handler(i);check();assert.ok(response.components.at(-1).components.slice(0,2).every(b=>b.disabled));
  t.model.save(buyer,quote);await handler(i);check();
  for(let n=2;n<=6;n++)t.model.save(buyer,{...quote,countryId:n});await handler(i);check();i.customId='favorites:1';await handler(i);check();
  i.customId='active_orders:0';await handler(i);check();t.sql.prepare("INSERT INTO orders(id,discord_id,status) VALUES(1,?,'ACTIVE')").run(buyer);await handler(i);check();
});

test('proof button opens native upload modal directly without slash command; legacy library uses link form',async()=>{let opened;class ModalFields{getUploadedFiles(){}}const native=createEfficiencyHandler({discord:{...discord,ModalSubmitFields:ModalFields}});const i={customId:'manual_upload',user:{id:buyer},showModal:async m=>opened=m};await native(i);assert.equal(opened.custom_id,'manual_upload_submit');assert.equal(opened.components[1].component.type,19);assert.equal(opened.components[1].component.max_values,1);const fallback=createEfficiencyHandler({discord});await fallback(i);assert.equal(opened.custom_id,'manual_request_submit');assert.equal(opened.components[0].type,1);assert.ok(!JSON.stringify(opened).includes('/bukti'));});
test('native proof modal submits image privately for admin approval and rejects invalid data before write',async()=>{let submitted,response;const h=createEfficiencyHandler({discord,features:{submit:r=>{submitted=r;return r;},poll:async()=>{}}});const attachment={url:'https://cdn.discordapp.com/attachments/123/456/proof.png',size:1024,contentType:'image/png'};let amount='5000',files={size:1,first:()=>attachment};const i={id:'100000000000000001',customId:'manual_upload_submit',user:{id:buyer},fields:{getUploadedFiles:()=>files,getTextInputValue:k=>k==='amount'?amount:'catatan'},deferReply:async p=>assert.equal(p.ephemeral,true),editReply:async p=>response=p};await h(i);assert.equal(submitted.amount,5000);assert.equal(submitted.userId,buyer);assert.equal(submitted.proof,attachment.url);assert.match(response.content,/memeriksa/);submitted=null;amount='5.000';await h(i);assert.equal(submitted,null);amount='5000';files={size:2};await h(i);assert.equal(submitted,null);files={size:1,first:()=>({...attachment,contentType:'application/pdf'})};await h(i);assert.equal(submitted,null);});
test('summary separates processing, unsent completed delivery and available stock from reserved stock and disabled products',()=>{
 const t=setup();t.sql.exec(`CREATE TABLE manual_product_orders(state TEXT,notified INTEGER);
 INSERT INTO manual_product_orders VALUES('pending',0),('completed',0),('completed',1),('refunded',0),('awaiting_payment',0);
 CREATE TABLE manual_products(id INTEGER,deleted INTEGER,enabled INTEGER,quantity INTEGER,auto_enabled INTEGER);
 CREATE TABLE manual_product_stock(product_id INTEGER,state TEXT);
 INSERT INTO manual_products VALUES(1,0,1,20,1),(2,0,1,3,0),(3,0,0,0,1),(4,1,1,0,1),(5,0,1,20,1);
 INSERT INTO manual_product_stock VALUES(1,'available'),(1,'reserved'),(1,'sold'),(5,'available'),(5,'available'),(5,'available'),(5,'available');`);
 const r=t.model.summary(admin);assert.equal(r.processing,1);assert.equal(r.delivery,1);assert.equal(r.lowStock,2);assert.throws(()=>t.model.summary(buyer));t.sql.close();
});
