// Local UI translations. Product names, account data and input values are never translated.
const phrases = new Map(Object.entries({
  'Panel Toko':'Store Panel','DM Gagal':'Failed DMs','Cari Pesanan':'Search Orders','Invoice / bukti transaksi (opsional)':'Invoice / receipt (optional)','Nama produk (opsional)':'Product name (optional)','Tanggal WIB YYYY-MM-DD (opsional)':'WIB date YYYY-MM-DD (optional)','Pasang / Perbarui Panel':'Post / Update Panel','Hapus Panel':'Delete Panel','Ya, Hapus Panel':'Yes, Delete Panel','Menunggu pembayaran QRIS':'Awaiting QRIS payment','Menunggu admin':'Awaiting admin','Selesai':'Completed','Dibatalkan • saldo dikembalikan':'Cancelled • refunded to balance','Konfirmasi Pembelian':'Confirm Purchase','Bayar Pakai Saldo':'Pay with Balance','Bayar Langsung QRIS':'Pay with QRIS','Biaya QRIS pembeli':'Customer QRIS fee','Gunakan Voucher':'Use Voucher','Pindai QRIS untuk membayar.':'Scan QRIS to pay.','Pastikan produk dan harga terbaru sudah benar sebelum melanjutkan.':'Check the product and current price before continuing.','Refund harga produk masuk ke saldo bot, termasuk pembayaran QRIS. Biaya QRIS tidak ikut dikembalikan. Pesanan yang sudah menerima OTP tidak dapat dibatalkan. Tekan Panduan Refund untuk detail.':'Product refunds go to your store balance, including QRIS purchases. QRIS fees are excluded. Orders that have received an OTP cannot be cancelled. See the Refund Guide for details.','Pesanan dibuat otomatis setelah pembayaran terkonfirmasi. Stok diperiksa setelah pembayaran; jika habis, harga produk dikembalikan ke saldo bot. Biaya QRIS tidak dikembalikan otomatis. Lihat hasil di tombol Cek Pembayaran; OTP dikirim melalui DM saat masuk.':'Your order is created after payment confirmation. Stock is checked after payment; if unavailable, the product price is refunded to your store balance. QRIS fees are not refunded automatically. Check Payment shows your order; an incoming OTP is sent by DM.','Harga & Modal':'Price & Cost','Modal/unit IDR (kosong = belum tahu)':'Cost/unit IDR (blank = unknown)','Modal per unit':'Cost per unit','Kesiapan Toko':'Store Readiness','Tes DM Admin':'Test Admin DM','Pesanan Terlambat':'Overdue Orders','Cocokkan Transaksi':'Reconcile Records','Tes Pemulihan':'Test Recovery','Bahasa':'Language','Pilih Bahasa':'Choose Language','Bahasa tersimpan.':'Language saved.',
  'Menu Awal':'Home','Menu Awal Admin':'Admin Home','Kembali':'Back','Sebelumnya':'Previous','Berikutnya':'Next','Perbarui':'Refresh','Mulai Ulang':'Start Over','Tutup Panel':'Close Panel','Batal':'Cancel',
  'Beli OTP':'Buy OTP','Produk Lainnya':'Other Products','Saldo':'Balance','Pesanan':'Orders','Isi Saldo':'Top Up','Bantuan':'Help','Saldo Anda':'Your Balance','Pesanan Saya':'My Orders','Riwayat Pesanan':'Order History','Riwayat OTP':'OTP History','OTP Aktif':'Active OTP','Invoice':'Invoice','Beli Lagi':'Buy Again','Cek OTP':'Check OTP','Batalkan':'Cancel',
  'Selamat datang di Produk Digital by Maboyy':'Welcome to Digital Products by Maboyy','est. 2020 — Bot Otomatis 24/7':'est. 2020 — Automated Bot 24/7',
  'Panel Admin':'Admin Panel','Toko':'Store','Pembeli':'Customers','Pembayaran':'Payments','Laporan':'Reports','Sistem':'System','Ringkasan':'Overview',
  'Pilih kategori untuk mengelola Hi, Belanja Produk Digital Yukk.':'Choose a category to manage your digital store.',
  'Pilih kategori yang ingin dikelola.':'Choose a category to manage.',
  'OTP Provider':'OTP Provider','Promo':'Promotions','Atur Harga OTP':'OTP Pricing','Lihat Layanan':'Browse Services','Kelola Produk':'Manage Products','Cari Produk':'Search Products','Cari Lagi':'Search Again','Hasil Pencarian Produk':'Product Search Results','Klaim Garansi':'Warranty Claims','Kelola Voucher':'Manage Vouchers','Buat Voucher':'Create Voucher',
  'Kelola Pembeli':'Manage Customers','Tambah Saldo':'Add Balance','Riwayat Saldo Manual':'Manual Balance History','Tiket Bantuan':'Support Tickets','Pengguna Bot':'Bot Users','Daftar Saldo Pembeli':'Customer Balances','Daftar Saldo':'Balance List','Cari Pembeli':'Find Customer','Semua Akun':'All Accounts','Memiliki Saldo':'With Balance','Saldo Nol':'Zero Balance','Aktif':'Active','Arsip':'Archived','Diarsipkan':'Archived','Dihapus':'Deleted','Hapus Pembeli':'Delete Customer','Arsipkan':'Archive','Pulihkan':'Restore',
  'Pesanan & Verifikasi':'Orders & Verification','Pemeriksaan':'Checks','Riwayat & Petunjuk':'History & Instructions','Pesanan Produk':'Product Orders','Pengajuan Saldo Manual':'Manual Top-Up Requests','Perlu Diperiksa':'Needs Review','Cek Topup Tertunda':'Check Pending Top-Ups','Riwayat Isi Saldo':'Top-Up History','Riwayat QRIS Beli':'QRIS Purchase History','Petunjuk Bayar Manual':'Manual Payment Instructions','Pemeriksaan Pembayaran':'Payment Checks',
  'Hari Ini':'Today','Bulan Ini':'This Month','Ekspor CSV':'Export CSV','Riwayat Biaya Gateway':'Gateway Fee History','Ubah Catatan':'Edit Note','Hapus Catatan':'Delete Note',
  'Akses Bot':'Bot Access','Provider & Webhook':'Provider & Webhook','Data & Pemeliharaan':'Data & Maintenance','Admin Toko':'Store Admins','Server & Channel':'Servers & Channels','Saldo Provider (Owner)':'Provider Balance (Owner)','Beli OTP Provider (Owner)':'Buy Provider OTP (Owner)','Tes Webhook SMSCode':'Test SMSCode Webhook','Peringatan Saldo':'Balance Alerts','Backup (Owner)':'Backup (Owner)','Aktivitas Admin':'Admin Activity','Maintenance':'Maintenance','Ping & Kecepatan Bot':'Bot Ping & Response','Tes Ulang':'Test Again',
  'Backup Sekarang':'Back Up Now','Unduh Backup':'Download Backup','Matikan Jadwal':'Disable Schedule','Aktifkan Jadwal':'Enable Schedule','Setujui':'Approve','Tolak':'Reject','Cabut Izin':'Revoke Access','Tambah Admin':'Add Admin','Hapus Admin':'Remove Admin','Atur Channel':'Set Channel','Atur Role':'Set Role','Hapus Role':'Remove Role',
  'QRIS Otomatis':'Automatic QRIS','Manual':'Manual','Cek Saldo':'Check Balance','Bayar Saldo':'Pay with Balance','Bayar QRIS':'Pay with QRIS','Hubungi Admin':'Contact Admin','Kirim Bukti Pembayaran':'Submit Payment Proof','Pengajuan Saya':'My Requests','Cek Pembayaran & Pesanan':'Check Payment & Order','Cek QRIS & Pesanan':'Check QRIS & Order','Cek Pembayaran':'Check Payment','Riwayat Topup':'Top-Up History',
  'Ubah Produk':'Edit Product','Data & Stok':'Data & Stock','Pengaturan':'Settings','Nama & Deskripsi':'Name & Description','Harga Jual':'Selling Price','Atur Harga Jual':'Set Selling Price','Data Produk':'Product Data','Tambah Data Produk':'Add Product Data','Atur Stok Jual':'Set Sale Stock','Ubah Stok Jual':'Edit Sale Stock','Lihat Contoh':'Preview','Tes Beli':'Test Purchase','Hapus Produk':'Delete Product','Ya, Hapus Produk':'Yes, Delete Product','Nonaktifkan':'Deactivate','Aktifkan':'Activate','Matikan Kirim Otomatis':'Disable Auto Delivery','Aktifkan Kirim Otomatis':'Enable Auto Delivery','Varian, Panduan & Garansi':'Variants, Guide & Warranty','Panduan & Garansi':'Guide & Warranty','Pilih Varian':'Choose Variant','Tambah Varian':'Add Variant','Notifikasi Stok':'Stock Alert','Kirim / Selesaikan':'Deliver / Complete','Batalkan & Refund':'Cancel & Refund','Produk Manual':'Digital Products','Pesanan Produk Manual':'Digital Product Orders',
  'Menunggu':'Pending','Selesai':'Resolved','Ditolak':'Rejected','Semua':'All','Balas':'Reply','Tutup Tiket':'Close Ticket','Buat Tiket Bantuan':'Create Support Ticket','Tiket Saya':'My Tickets','Panduan Pembeli Baru':'New Customer Guide','Panduan Refund':'Refund Guide','Favorit Saya':'My Favorites','Cari Aplikasi':'Search Apps','Cari Negara':'Search Countries','Pilih Aplikasi':'Choose App','Pilih Negara':'Choose Country','Pilih Operator':'Choose Operator','Pilih Produk':'Choose Product','Simpan Favorit':'Save Favorite','Hapus Favorit':'Remove Favorite','Masukkan Voucher':'Enter Voucher',
  'Akun, saldo, dan bantuan pembeli.':'Customer accounts, balances and support.',
  'Pilih kategori pembayaran.':'Choose a payment category.',
  'Proses pesanan dan bukti pembayaran manual.':'Process orders and manual payment proofs.',
  'Periksa pembayaran bermasalah atau tertunda.':'Review payments with issues or pending payments.',
  'Riwayat transaksi dan petunjuk pembayaran manual.':'Transaction history and manual payment instructions.',
  'Penjualan, biaya, dan ekspor CSV.':'Sales, fees and CSV exports.',
  'Pilih kategori pengaturan bot.':'Choose a bot settings category.',
  'Kelola admin serta izin server, channel, dan role pengguna bot.':'Manage admins and access by server, channel and role.',
  'Saldo, pembelian owner, tes webhook, dan peringatan provider.':'Provider balance, owner purchases, webhook testing and alerts.',
  'Backup data, aktivitas admin, dan status operasional toko.':'Backups, admin activity and store operating status.',
  'Periksa katalog SMSCode atau atur markup harga jual OTP.':'Browse the SMSCode catalog or set the OTP selling markup.',
  'Buat voucher dan atur status promo toko.':'Create vouchers and manage store promotions.',
  'Pilih Kelola Produk untuk menambah produk, mengubah data, stok, harga jual, status, atau menghapus produk.':'Use Manage Products to add products or edit product data, stock, price and status, or delete products.',
  'Pilih produk di bawah.':'Choose a product below.','Pilih pesanan untuk melihat detail.':'Choose an order to see its details.','Belum ada pesanan.':'No orders yet.','Anda belum memiliki pesanan.':'You have no orders yet.','Belum ada transaksi.':'No transactions yet.','Belum ada akun pembeli tersimpan.':'No customer accounts saved yet.','Belum ada akun pada filter ini.':'No accounts match this filter.','Belum ada penambahan saldo manual.':'No manual balance credits yet.','Tidak ada pembayaran yang perlu diperiksa.':'No payments need review.',
  'Pilih produk atau varian untuk mengelolanya.':'Select a product or variant to manage.','Tidak ada produk yang cocok.':'No matching products.',
  'Saldo tidak cukup. Isi saldo dahulu.':'Insufficient balance. Please top up first.',
  'Produk sedang nonaktif.':'This product is inactive.','Produk tidak ditemukan.':'Product not found.','Pesanan tidak ditemukan.':'Order not found.','Akses ditolak.':'Access denied.','Akses admin sudah dicabut.':'Your admin access has been revoked.','Akses ditolak. ID Discord Anda belum terdaftar sebagai admin toko.':'Access denied. Your Discord account is not registered as a store admin.',
  'Hanya owner dapat melihat saldo dan membeli langsung dari provider.':'Only the owner can view the provider balance and purchase directly from the provider.',
  'Pencarian kedaluwarsa. Cari produk kembali.':'Search expired. Please search again.','Filter klaim tidak dikenal.':'Unknown claim filter.','Filter saldo tidak dikenal.':'Unknown balance filter.',
  'Pembeli':'Customer','Produk':'Product','Harga':'Price','Harga jual':'Selling price','Stok jual':'Sale stock','Stok tersedia':'Available stock','Data produk tersedia':'Available product data','Data siap kirim':'Ready-to-send data','Status':'Status','Status pengiriman':'Delivery mode','Deskripsi':'Description','Tagihan':'Invoice','Order provider':'Provider order','Biaya provider':'Provider cost','Saldo saat ini':'Current balance','Saldo setelah transaksi':'Balance after transaction','Total saldo akun aktif':'Total active account balance','Jumlah akun':'Accounts','Tampilan':'Filter','Kata':'Search','Garansi sampai':'Warranty until','Masa aktif berakhir':'Expires on','Pembayaran':'Payment','ID Discord Anda':'Your Discord ID','Admin':'Admin','Catatan':'Note','Koneksi Discord':'Discord connection','Proses hingga respons awal':'Time to initial response','Akses database':'Database access','RAM proses':'Process memory','Waktu berjalan':'Uptime',
  'Nama produk':'Product name','Nama produk / varian':'Product / variant name','Jumlah stok jual (angka)':'Sale stock (number)','Data DM unik: 1 akun/kode (opsional)':'Unique DM data: 1 account/code (optional)','Deskripsi & waktu proses':'Description & processing time','Harga jual IDR, tanpa titik':'Selling price in IDR, digits only','ID Discord pengguna pembeli':'Customer Discord user ID','Nominal rupiah (minimal 5000, tanpa titik)':'Amount in IDR (minimum 5000, digits only)','Catatan / referensi pembayaran':'Note / payment reference','Tambah Produk Manual':'Add Digital Product','Tambah Saldo Pembeli':'Add Customer Balance','Cari Pembeli':'Find Customer',
  'Latensi lebih rendah berarti respons lebih cepat. Nilai koneksi berasal dari heartbeat Discord.':'Lower latency means faster responses. Connection latency comes from the Discord heartbeat.',
  'Cepat':'Fast','Cukup responsif':'Responsive','Latensi tinggi':'High latency','Menunggu koneksi':'Waiting for connection','Belum tersedia':'Not available',
  '🔒 Menu bot melalui DM hanya untuk admin toko. Untuk belanja, cek saldo, isi saldo, atau melihat pesanan, buka /shop di server Discord yang sudah disetujui. Data pesanan tetap dikirim ke DM Anda.':'🔒 Bot menus in DMs are for store admins only. To shop, check your balance, top up or view orders, open /shop in an approved Discord server. Order data is still delivered to your DMs.',
  '🔒 Server ini belum mendapat izin admin toko. Minta admin membuka /admin → Sistem → Server & Channel untuk verifikasi.':'🔒 This server is not approved yet. Ask a store admin to open /admin → System → Servers & Channels for verification.',
  'Pembayaran saldo atau QRIS. Produk dengan stok otomatis dikirim setelah pembayaran terverifikasi.':'Pay with balance or QRIS. Products with automatic stock are delivered once payment is verified.',
  '1. Pilih **Beli OTP** atau **Produk Lainnya**.\n2. Baca deskripsi dan harga, lalu konfirmasi.\n3. Bayar memakai saldo toko atau QRIS jika tersedia. Isi saldo minimal **5.000 IDR**.\n4. QRIS belum terkonfirmasi? Buka **Pesanan → Invoice → Cek Pembayaran & Pesanan**. Gunakan tagihan yang sama.\n5. Produk otomatis dan OTP dikirim melalui DM. Aktifkan izin DM dari anggota server. Produk yang diproses admin mengikuti waktu pada deskripsi.\n6. Lihat hasil melalui **Pesanan → Riwayat Pesanan**. Tombol **Beli Lagi** membuka konfirmasi baru dengan harga terbaru.':'1. Choose **Buy OTP** or **Other Products**.\n2. Read the description and price, then confirm.\n3. Pay with store balance or QRIS when available. Minimum top-up: **5,000 IDR**.\n4. QRIS not confirmed? Open **Orders → Invoice → Check Payment & Order**. Use the same invoice.\n5. Automatic products and OTPs are delivered by DM. Allow DMs from server members. Admin-processed products follow the time stated in their description.\n6. View results in **Orders → Order History**. **Buy Again** opens a new confirmation at the current price.',
  '**Cara membeli OTP**\n1. Klik **Beli OTP**\n2. Pilih aplikasi, negara, operator, dan harga\n3. Konfirmasi pembelian\n4. Nomor akan diberikan\n5. OTP dikirim melalui DM saat masuk; **Cek OTP** tetap tersedia\n\nJika order gagal, hubungi admin toko.':'**How to buy an OTP**\n1. Click **Buy OTP**\n2. Choose the app, country, operator and price\n3. Confirm the purchase\n4. You will receive a number\n5. The OTP is delivered by DM when received; **Check OTP** remains available\n\nIf an order fails, contact the store admin.'
}));
for(const [source,target] of Object.entries({
  'Varian Produk':'Product Variants','Panduan & Masa Aktif':'Guide & Duration','Layanan Premium':'Premium Product Settings','Jawaban Admin':'Admin Response','Selesaikan / Kirim Penggantian':'Resolve / Send Replacement','Tolak dengan Alasan':'Reject with Reason','Panduan Penggunaan':'Usage Guide','Hasil / keterangan pengiriman':'Delivery Data / Notes','Detail Produk':'Product Details','Klaim Garansi • Menunggu':'Warranty Claims • Pending','Klaim Garansi • Selesai':'Warranty Claims • Resolved','Klaim Garansi • Ditolak':'Warranty Claims • Rejected','Klaim Garansi • Semua':'Warranty Claims • All',
  'Pilih durasi atau jenis akun. Harga ditampilkan setelah varian dipilih.':'Select a duration or account type. The price is shown after you select a variant.','Belum ada varian.':'No variants yet.','Pilih data untuk mengubah akun atau kode. Satu data unik untuk satu pembeli.':'Select a data entry to edit an account or code. Each unique entry is for one customer.',
  'Otomatis':'Automatic','Nonaktif':'Inactive','Aktif':'Active','Ya':'Yes','Tidak':'No','Belum':'Not yet','Menunggu verifikasi':'Awaiting verification','Disetujui':'Approved','Izin dicabut':'Access revoked','Siap kirim':'Ready to send','Tersedia':'Available','Terjual':'Sold','Dipesan':'Reserved','Berhasil':'Successful','Gagal':'Failed','Dibatalkan':'Cancelled','Menunggu Pembayaran':'Awaiting Payment','Menunggu Admin':'Awaiting Admin','Kedaluwarsa':'Expired',
  'Total saldo akun':'Total account balance','Data DM siap kirim':'Ready-to-send DM data','Masa aktif':'Validity period','Garansi':'Warranty','Kendala':'Issue','ID Pembeli':'Customer ID','Saldo masuk':'Balance credited','Nominal':'Amount','Jumlah':'Quantity','Metode':'Method','Waktu':'Time','Tanggal':'Date','Kode Voucher':'Voucher Code','Potongan':'Discount','Biaya':'Fee','Harga produk':'Product price','Total pembayaran':'Payment total','Nomor':'Number','Aplikasi':'App','Negara':'Country','Operator':'Operator','Refund':'Refund','Mata uang':'Currency','Stok':'Stock','Durasi':'Duration',
  'Isi Saldo Manual':'Manual Top-Up','Riwayat Isi Saldo QRIS':'QRIS Top-Up History','Riwayat QRIS Beli':'QRIS Purchase History','Pengajuan Isi Saldo':'Top-Up Request','Tambah Data':'Add Data','Data Produk #':'Product Data #','Setujui Saldo':'Approve Balance Credit','Tolak Pengajuan':'Reject Request','Lihat Bukti':'View Proof','Unggah Bukti':'Upload Proof','Konfirmasi Pembelian':'Confirm Purchase','Konfirmasi Beli':'Confirm Purchase','Konfirmasi':'Confirm','Tes Beli Admin':'Admin Test Purchase',
  'Pengaturan Pembayaran Manual':'Manual Payment Settings','Peringatan Saldo Provider':'Provider Balance Alert','Hubungkan Pesanan':'Link Order','Refund ke Saldo':'Refund to Balance','Hubungkan Pesanan Provider':'Link Provider Order','Kembalikan ke Saldo Pembeli':'Refund Customer Balance','Laporan & Operasional':'Reports & Operations','Laporan Hari Ini':'Today’s Report','Laporan Bulan Ini':'Monthly Report',
  'Pilih menu di bawah untuk melanjutkan.':'Choose a menu below to continue.','Tekan tombol pilihan untuk melanjutkan.':'Select a button to continue.','Saldo manual masuk setelah disetujui admin. Tekan Saldo untuk mengecek hasilnya.':'Manual top-ups are credited after admin approval. Click Balance to check the result.',
  'Toko sedang maintenance. Pembelian baru dihentikan sementara. Pesanan, OTP, dan tagihan sebelumnya tetap tersedia.':'The store is under maintenance. New purchases are paused. Existing orders, OTPs and invoices remain available.',
  '🔧 Toko sedang maintenance. Pembelian baru dihentikan sementara. Pesanan, OTP, dan tagihan sebelumnya tetap tersedia.':'🔧 The store is under maintenance. New purchases are paused. Existing orders, OTPs and invoices remain available.',
  'Nama produk baru':'New product name','Produk baru':'New product','Jelaskan produk dan perkiraan waktu proses.':'Describe the product and its expected processing time.','Nama varian':'Variant name','Panduan penggunaan':'Usage instructions','Durasi aktif (hari, 0=nonaktif)':'Validity in days (0=disabled)','Garansi (hari, 0=nonaktif)':'Warranty in days (0=disabled)',
  'Bukti pembayaran':'Payment proof','Catatan pembeli':'Customer note','Nama lengkap':'Full name','Alamat email':'Email address','Email pembayaran':'Payment email','Nominal isi saldo':'Top-up amount','Keluhan / kendala':'Problem / issue','Pesan':'Message','Balasan':'Reply','Data pengiriman':'Delivery data','Nama & deskripsi':'Name & description'
}))phrases.set(source,target);
for(const [source,target] of Object.entries({
  'Belum ada produk manual tersedia.':'No digital products are available yet.','Invoice & Bukti Transaksi':'Invoices & Receipts','Pilih pesanan untuk melihat invoice, status, dan hasil.':'Choose an order to see its invoice, status and delivery.','Detail Pesanan':'Order Details','Status Pengajuan':'Request Status','Buka Tagihan Aktif':'Open Active Invoice','Isi Saldo QRIS':'QRIS Top-Up','Nonaktifkan Produk':'Deactivate Product','Aktifkan Produk':'Activate Product','Coba Lagi':'Try Again','Minimal isi saldo **5.000 IDR**.':'Minimum top-up: **5,000 IDR**.',
  '**QRIS Otomatis** — saldo masuk setelah pembayaran terverifikasi.':'**Automatic QRIS** — balance is credited once payment is verified.',
  '**Manual** — hubungi admin dan kirim bukti pembayaran; saldo ditambahkan setelah diperiksa.':'**Manual** — contact the admin and submit payment proof; balance is credited after review.',
  'QRIS belum aktif. Admin perlu mengisi konfigurasi pembayaran. Anda tetap bisa memakai Isi Saldo → Manual.':'QRIS is not enabled. An admin must configure payments. You can still use Top Up → Manual.',
  'Masih ada tagihan QRIS aktif. Lanjutkan tagihan sebelumnya.':'An active QRIS invoice already exists. Continue with your existing invoice.',
  '1. Hubungi admin untuk meminta tujuan pembayaran dan konfirmasi nominal.':'1. Contact the admin for payment details and confirm the amount.',
  '2. Lakukan pembayaran sesuai petunjuk admin.':'2. Pay according to the admin’s instructions.',
  '3. Kirim bukti pembayaran dan ID Discord Anda kepada admin.':'3. Submit your payment proof and Discord user ID to the admin.',
  '4. Setelah pembayaran diperiksa, admin menambahkan saldo.':'4. Once payment is reviewed, the admin credits your balance.',
  'Tekan Kirim Bukti Pembayaran untuk membuka formulir bukti pembayaran. Admin memeriksa mutasi sebelum menyetujui. Tekan Status Pengajuan untuk melihat hasilnya.':'Click Submit Payment Proof to open the form. The admin verifies the payment before approving it. Click Request Status to view the result.',
  'Data dikirim setelah pembayaran terverifikasi.':'Data is delivered once payment is verified.'
}))phrases.set(source,target);
function text(value) {
  if(typeof value!=='string')return value;
  if(phrases.has(value))return phrases.get(value);
  // Only translate known headings and field prefixes; suffixes are left verbatim.
  return value.split('\n').map(line=>{
    if(phrases.has(line))return phrases.get(line);
    const page=line.match(/^Halaman (\d+)\/(\d+)(?: • (\d+) (produk|pesanan|akun|pilihan|hasil))?(.*)$/);
    if(page)return 'Page '+page[1]+'/'+page[2]+(page[3]?' • '+page[3]+' '+({produk:'products',pesanan:'orders',akun:'accounts',pilihan:'options',hasil:'results'}[page[4]]):'')+page[5];
    const numbered=line.match(/^(\d+) klaim • Halaman (\d+)\/(\d+)$/);
    if(numbered)return numbered[1]+' claims • Page '+numbered[2]+'/'+numbered[3];
    const m=line.match(/^(\s*(?:[\p{Extended_Pictographic}\uFE0F\s]+)?\*{0,2})([^:*•\n]+?)(\*{0,2})(:| • | — |$)(.*)$/u);
    if(m && phrases.has(m[2].trim()))return m[1]+phrases.get(m[2].trim())+m[3]+m[4]+(['Status','Status pengiriman','Pembayaran','Saldo masuk','Koneksi Discord'].includes(m[2].trim())&&phrases.has(m[5].trim())?phrases.get(m[5].trim()):m[5]);
    return line;
  }).join('\n');
}
function createLanguages({db,staff}) {
  db.exec('CREATE TABLE IF NOT EXISTS bot_languages(discord_id TEXT PRIMARY KEY,language TEXT NOT NULL CHECK(language IN (\'id\',\'en\')))');
  function get(id){return db.prepare('SELECT language FROM bot_languages WHERE discord_id=?').get(String(id))?.language || 'id';}
  function selected(id){return Boolean(db.prepare('SELECT 1 FROM bot_languages WHERE discord_id=?').get(String(id)));}
  function set(id,language){if(!/^\d{17,20}$/.test(String(id))||!['id','en'].includes(language))throw Error('Pilihan bahasa tidak valid.');db.prepare('INSERT INTO bot_languages(discord_id,language) VALUES(?,?) ON CONFLICT(discord_id) DO UPDATE SET language=excluded.language').run(String(id),language);}
  const serialize=value=>typeof value?.toJSON==='function'?value.toJSON():value;
  function translate(payload,id,context='') {
    if(get(id)!=='en')return payload;
    const p=serialize(typeof payload==='string'?{content:payload}:payload),out={...p};
    // These screens contain private/customer-authored data. Keep their bodies intact.
    const privateBody=/(?:manual_order:|manual_deliver|manual_stock_edit|tools_ticket|tool_ticket|tools_reply|tool_reply|premium_claim(?:_|:)|premium_resolve|history_detail:|history_list:|history_search_|^shop_orders$|^shop_order_history$|^direct_history$)/.test(context)||context==='delivery';
    if(!privateBody&&typeof p.content==='string')out.content=text(p.content);
    const productBody=/(?:manual_(?!catalog|orders|search)|premium_|history_detail)/.test(context);
    if(p.embeds)out.embeds=p.embeds.map(raw=>{const e=serialize(raw),r={...e};if(!privateBody&&!productBody&&e.title)r.title=text(e.title);if(!privateBody&&!productBody&&e.description)r.description=text(e.description);if(e.footer)r.footer={...e.footer,text:text(e.footer.text)};if(e.fields)r.fields=e.fields.map(f=>({...f,name:text(f.name)}));return r;});
    if(p.title)out.title=text(p.title).slice(0,45);
    if(p.components)out.components=p.components.map(raw=>{const r=serialize(raw);return {...r,components:(r.components||[]).map(raw=>{const c=serialize(raw),copy={...c};const namedChoice=/^(?:flow_pick:|provider_flow_pick:|pick_product:|provider_product:|product:|manual_detail:|admin_manual_detail:|manual_order:|admin_manual_order:|history_detail:|premium_variant:|admin_premium_variant:|admin_premium_claim_detail:)/.test(c.custom_id||'');if(c.label&&!namedChoice)copy.label=text(c.label).slice(0,c.type===4?45:80);if(c.placeholder)copy.placeholder=text(c.placeholder);return copy;})};});
    return out;
  }
  function attach(i){for(const method of ['reply','editReply','update','followUp','showModal']){if(typeof i[method]!=='function')continue;const original=i[method].bind(i);i[method]=(p,...args)=>original(translate(p,i.user.id,i.customId||i.commandName),...args);}}
  async function onboard(i){
    const purchase=/^(?:shop_home$|shop_products$|shop_manual_products$|flow_|pick_product:|buy_again:|confirm_buy:|qris_buy:|manual_quote:|manual_buy:|manual_qris:|direct_email:|manual_qris_email:)/.test(String(i.customId||''));
    if(i.customId!=='shop_start'&&(selected(i.user.id)||!(i.isChatInputCommand?.()&&i.commandName==='shop'||purchase)))return false;
    await i.reply({ephemeral:true,content:'**Selamat datang / Welcome**\nPilih bahasa sebelum mulai berbelanja.\nChoose your language before shopping.',components:[{type:1,components:[{type:2,custom_id:'shop_language_set:id:start',label:'Bahasa Indonesia',style:1},{type:2,custom_id:'shop_language_set:en:start',label:'English',style:1}]}]});return true;
  }
  async function handle(i,shopPayload){const parts=String(i.customId||'').split(':');if(!['shop_language','shop_language_set'].includes(parts[0]))return false;const context=parts[0]==='shop_language_set'?parts[2]:parts[1],admin=context==='admin';if(!['admin','shop','start'].includes(context)||admin&&!staff.isAdmin(i.user.id)){await i.reply({ephemeral:true,content:'Akses ditolak.'});return true;}
    if(parts[0]==='shop_language_set')set(i.user.id,parts[1]);
    if(context==='start'&&parts[0]==='shop_language_set'&&shopPayload){await i.reply({...shopPayload(),ephemeral:true});return true;}
    const lang=get(i.user.id),message={ephemeral:true,content:(parts[0]==='shop_language_set'?'Bahasa tersimpan.\n\n':'')+'**Pilih Bahasa / Choose Language**\nBahasa Indonesia / English',components:[{type:1,components:[{type:2,custom_id:'shop_language_set:id:'+context,label:'Bahasa Indonesia',style:lang==='id'?3:1,disabled:lang==='id'},{type:2,custom_id:'shop_language_set:en:'+context,label:'English',style:lang==='en'?3:1,disabled:lang==='en'}]},{type:1,components:[{type:2,custom_id:admin?'admin_home':'shop_home',label:admin?'Menu Awal Admin':'Menu Awal',style:1}]}]};
    // A new private response is intentional: do not edit a shared shop panel.
    await i.reply(message);return true;
  }
  return {get,set,selected,translate,attach,handle,onboard};
}
module.exports={createLanguages,text};
