const {buyerLabel,rememberBuyer,hydrateBuyers}=require('./buyer-profiles');
const fs=require('node:fs'),path=require('node:path'),{randomUUID}=require('node:crypto');
const {createCoupons}=require('./coupons');
const csvCell=v=>'"'+String(v ?? '').replace(/^[=+@-]/,"'$&").replace(/"/g,'""')+'"';
function createShopTools({db,staff,payments,smsCatalogProducts,pricing,sendDM,backupDir,now=Date.now}){
  db.exec(`CREATE TABLE IF NOT EXISTS shop_admin_audit(id INTEGER PRIMARY KEY,admin_id TEXT NOT NULL,action TEXT NOT NULL,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
  CREATE TABLE IF NOT EXISTS shop_tools_settings(key TEXT PRIMARY KEY,value TEXT NOT NULL);
  CREATE TABLE IF NOT EXISTS support_tickets(id TEXT PRIMARY KEY,discord_id TEXT NOT NULL,order_ref TEXT,status TEXT DEFAULT 'open',created_at TEXT DEFAULT CURRENT_TIMESTAMP);
  CREATE TABLE IF NOT EXISTS support_messages(id INTEGER PRIMARY KEY,ticket_id TEXT NOT NULL,author_id TEXT NOT NULL,role TEXT NOT NULL,body TEXT NOT NULL,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
  CREATE TABLE IF NOT EXISTS support_notifications(message_id INTEGER NOT NULL,discord_id TEXT NOT NULL,PRIMARY KEY(message_id,discord_id));
  CREATE TABLE IF NOT EXISTS stock_subscriptions(favorite_id INTEGER PRIMARY KEY,discord_id TEXT NOT NULL,last_available INTEGER DEFAULT 0,last_checked INTEGER DEFAULT 0);
  CREATE TABLE IF NOT EXISTS payment_fee_overrides(order_id TEXT PRIMARY KEY,fee INTEGER NOT NULL,note TEXT NOT NULL,admin_id TEXT NOT NULL,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
  CREATE TABLE IF NOT EXISTS topup_notifications(order_id TEXT PRIMARY KEY);`);
  if(!db.prepare('PRAGMA table_info(orders)').all().some(c=>c.name==='is_owner_test'))db.exec('ALTER TABLE orders ADD COLUMN is_owner_test INTEGER NOT NULL DEFAULT 0');
  for(const [column,type]of Object.entries({polled_at:'INTEGER',paid_at:'TEXT'}))if(!db.prepare('PRAGMA table_info(topups)').all().some(c=>c.name===column))db.exec(`ALTER TABLE topups ADD COLUMN ${column} ${type}`);
  if(!db.prepare('PRAGMA table_info(payment_fee_overrides)').all().some(c=>c.name==='record_key'))db.exec('ALTER TABLE payment_fee_overrides ADD COLUMN record_key TEXT');
  for(const f of db.prepare('SELECT order_id FROM payment_fee_overrides WHERE record_key IS NULL').all())db.prepare('UPDATE payment_fee_overrides SET record_key=? WHERE order_id=?').run(randomUUID(),f.order_id);
  const admin=id=>{if(!staff.isAdmin(id))throw new Error('Akses ditolak.');};
  const owner=id=>{if(!staff.isOwner(id))throw new Error('Hanya owner boleh mengelola/unduh backup database.');};
  const read=(k,f)=>db.prepare('SELECT value FROM shop_tools_settings WHERE key=?').get(k)?.value ?? f;
  const write=(k,v)=>db.prepare('INSERT INTO shop_tools_settings(key,value) VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value').run(k,String(v));
  const audit=(id,action)=>{admin(id);db.prepare('INSERT INTO shop_admin_audit(admin_id,action) VALUES(?,?)').run(id,String(action).slice(0,500));};
  const coupons=createCoupons({db,staff,audit,now});
  function ticket(id,user,ref,body){if(!/^\d{17,20}$/.test(id) || !/^\d{17,20}$/.test(user) || !body.trim() || body.length>1000)throw new Error('Pesan tiket wajib diisi, maksimal 1000 karakter.');ref=String(ref || '').trim();if(ref && !db.prepare('SELECT id FROM orders WHERE provider_order_id=? AND discord_id=?').get(ref,user))throw new Error('Pesanan tidak ditemukan pada akun Anda.');
    return db.transaction(()=>{const previous=db.prepare('SELECT * FROM support_tickets WHERE id=?').get(id);if(previous){if(previous.discord_id!==user)throw new Error('Tiket tidak ditemukan.');return previous;}if(db.prepare("SELECT COUNT(*) n FROM support_tickets WHERE discord_id=? AND status='open'").get(user).n>=3)throw new Error('Maksimal 3 tiket terbuka. Tunggu balasan admin.');db.prepare('INSERT INTO support_tickets(id,discord_id,order_ref) VALUES(?,?,?)').run(id,user,ref || null);db.prepare("INSERT INTO support_messages(ticket_id,author_id,role,body) VALUES(?,?,'buyer',?)").run(id,user,body.trim());return getTicket(id,user);})();
  }
  function getTicket(id,user,asAdmin=false){if(asAdmin)admin(user);const t=db.prepare('SELECT * FROM support_tickets WHERE id=?').get(id);if(!t || (!asAdmin && t.discord_id!==user))throw new Error('Tiket tidak ditemukan.');return {...t,messages:db.prepare('SELECT * FROM support_messages WHERE ticket_id=? ORDER BY id DESC LIMIT 5').all(id).reverse()};}
  function replyTicket(id,user,body,asAdmin=false,close=false){if(asAdmin)admin(user);if(!body.trim() || body.length>1000)throw new Error('Balasan 1–1000 karakter.');db.transaction(()=>{const t=getTicket(id,user,asAdmin);if(t.status!=='open')throw new Error('Tiket sudah ditutup.');if(close && !asAdmin)throw new Error('Hanya admin boleh menutup tiket.');db.prepare('INSERT INTO support_messages(ticket_id,author_id,role,body) VALUES(?,?,?,?)').run(id,user,asAdmin?'admin':'buyer',(close?'[TIKET DITUTUP] ':'')+body.trim());if(close)db.prepare("UPDATE support_tickets SET status='closed' WHERE id=?").run(id);if(asAdmin)audit(user,(close?'Tutup':'Balas')+' tiket '+id);})();}
  function pages(query,args,page,size=5){const count=db.prepare('SELECT COUNT(*) n FROM ('+query+')').get(...args).n,pages=Math.max(1,Math.ceil(count/size));page=Math.min(Math.max(Number.isSafeInteger(page)?page:0,0),pages-1);return {count,pages,page,rows:db.prepare(query+' LIMIT ? OFFSET ?').all(...args,size,page*size)};}
  function tickets(user,page=0,asAdmin=false){if(asAdmin)admin(user);return pages('SELECT * FROM support_tickets WHERE '+(asAdmin?"status='open'":'discord_id=?')+' ORDER BY created_at DESC,id DESC',asAdmin?[]:[user],page);}
  const dir=path.resolve(backupDir || './backups');let backupBusy=false,payBusy=false,notifyBusy=false,stockBusy=false;
  async function backup(id,force=false){if(id)owner(id);if(backupBusy)throw new Error('Backup sedang berjalan.');const day=new Date(now()+7*3600000).toISOString().slice(0,10);if(!force && (read('backup_enabled','1')!=='1' || read('backup_day','')===day))return;
    backupBusy=true;const file=path.join(dir,'shop-backup-'+now()+'-'+randomUUID()+'.db');try{fs.mkdirSync(dir,{recursive:true,mode:0o700});await db.backup(file);fs.chmodSync(file,0o600);write('backup_day',day);write('backup_last',path.basename(file));write('backup_error','');const entries=fs.readdirSync(dir).filter(n=>/^shop-backup-\d+-[a-f0-9-]+\.db$/.test(n)).sort((a,b)=>a===path.basename(file)?-1:b===path.basename(file)?1:Number(b.split('-')[2])-Number(a.split('-')[2]));for(const n of entries.slice(7))fs.unlinkSync(path.join(dir,n));if(id)audit(id,'Buat backup database');return file;}catch(e){write('backup_error','Backup gagal; periksa ruang volume dan log server.');try{fs.unlinkSync(file);}catch{}throw e;}finally{backupBusy=false;}}
  function backupStatus(id){owner(id);return {enabled:read('backup_enabled','1')==='1',last:read('backup_last','Belum ada'),error:read('backup_error','')};}
  function backupToggle(id){owner(id);write('backup_enabled',read('backup_enabled','1')==='1'?'0':'1');audit(id,'Ubah jadwal backup');}
  function downloadBackup(id){owner(id);const name=read('backup_last','');if(!/^shop-backup-\d+-[a-f0-9-]+\.db$/.test(name))throw new Error('Backup belum tersedia.');const file=path.join(dir,name);if(fs.statSync(file).size>8*1024*1024)throw new Error('Backup melebihi 8 MB. Unduh lewat Railway; jangan kirim database ke channel publik.');return file;}
  async function reconcile(){if(payBusy)return;payBusy=true;try{for(const p of db.prepare("SELECT * FROM topups WHERE purpose='topup' AND gateway IN ('tripay','midtrans') AND credited=0 AND status IN ('creating','pending') ORDER BY COALESCE(polled_at,0),created_at LIMIT 5").all()){db.prepare('UPDATE topups SET polled_at=? WHERE order_id=?').run(now(),p.order_id);try{await payments.refresh(p.order_id,p.discord_id);}catch{/* Never create a replacement charge after uncertainty. */}}
    if(sendDM)for(const p of db.prepare("SELECT * FROM topups t WHERE purpose='topup' AND credited=1 AND NOT EXISTS(SELECT 1 FROM topup_notifications n WHERE n.order_id=t.order_id) ORDER BY created_at LIMIT 20").all())try{await sendDM(p.discord_id,`Pembeli: ${buyerLabel(p.discord_id)}\n✅ Isi saldo ${p.amount.toLocaleString('id-ID')} IDR diterima. Tagihan: ${p.order_id}. Tekan Saldo di /shop.`);db.prepare('INSERT OR IGNORE INTO topup_notifications VALUES(?)').run(p.order_id);}catch{}
  }finally{payBusy=false;}}
  async function notifyTickets(){if(notifyBusy || !sendDM)return;notifyBusy=true;try{const admins=staff.ids(),buyers=db.prepare("SELECT DISTINCT t.discord_id FROM support_tickets t JOIN support_messages m ON m.ticket_id=t.id WHERE m.role='admin' AND NOT EXISTS(SELECT 1 FROM support_notifications n WHERE n.message_id=m.id AND n.discord_id=t.discord_id)").all().map(t=>t.discord_id);
    for(const recipient of new Set([...admins,...buyers]))for(const m of db.prepare("SELECT m.*,t.discord_id FROM support_messages m JOIN support_tickets t ON t.id=m.ticket_id WHERE ((m.role='buyer' AND ?=1) OR (m.role='admin' AND t.discord_id=?)) AND NOT EXISTS(SELECT 1 FROM support_notifications n WHERE n.message_id=m.id AND n.discord_id=?) ORDER BY m.id LIMIT 20").all(admins.includes(recipient)?1:0,recipient,recipient)){try{await sendDM(recipient,`🎫 Tiket ${m.ticket_id}\n${m.role==='admin'?'Balasan admin':'Pesan pembeli '+buyerLabel(m.discord_id)}: ${m.body}\nBuka ${m.role==='admin'?'Bantuan → Tiket Saya':'/admin → Pembeli → Tiket Bantuan'}.`);db.prepare('INSERT OR IGNORE INTO support_notifications VALUES(?,?)').run(m.id,recipient);}catch{}}
  }finally{notifyBusy=false;}}
  function subscribe(user,id){const f=db.prepare('SELECT * FROM buyer_favorites WHERE id=? AND discord_id=?').get(Number(id),user);if(!f)throw new Error('Favorit tidak ditemukan.');const s=db.prepare('SELECT * FROM stock_subscriptions WHERE favorite_id=? AND discord_id=?').get(f.id,user);if(s){db.prepare('DELETE FROM stock_subscriptions WHERE favorite_id=? AND discord_id=?').run(f.id,user);return false;}db.prepare('INSERT INTO stock_subscriptions(favorite_id,discord_id) VALUES(?,?)').run(f.id,user);return true;}
  async function stock(){if(stockBusy || !sendDM)return;stockBusy=true;try{db.prepare('DELETE FROM stock_subscriptions WHERE NOT EXISTS(SELECT 1 FROM buyer_favorites f WHERE f.id=stock_subscriptions.favorite_id AND f.discord_id=stock_subscriptions.discord_id)').run();for(const f of db.prepare('SELECT s.*,f.app,f.country,f.operator,f.name FROM stock_subscriptions s JOIN buyer_favorites f ON f.id=s.favorite_id AND f.discord_id=s.discord_id ORDER BY last_checked LIMIT 5').all()){db.prepare('UPDATE stock_subscriptions SET last_checked=? WHERE favorite_id=?').run(now(),f.favorite_id);try{const filters={platform_id:f.app,country_id:f.country};if(f.operator!=='any')filters.operator_id=f.operator;const data=await smsCatalogProducts(filters),available=data.data.filter(p=>String(p.platform_id)===f.app && String(p.country_id)===f.country && (p.operator_id==null?'any':String(p.operator_id))===f.operator && p.active && Number(p.available)>0);if(available.length && !f.last_available){const price=Math.min(...available.map(p=>pricing.price(p.price?.canonical_amount ?? p.price)));await sendDM(f.discord_id,`⭐ Stok favorit tersedia: ${f.name}\nHarga mulai ${price.toLocaleString('id-ID')} IDR. Buka Beli OTP → Favorit Saya. Harga/stok bisa berubah; nomor belum dipesan.`);}db.prepare('UPDATE stock_subscriptions SET last_available=? WHERE favorite_id=?').run(available.length?1:0,f.favorite_id);}catch{}}}finally{stockBusy=false;}}
  function fee(id,orderId,value,note){admin(id);const p=db.prepare('SELECT * FROM topups WHERE order_id=? AND credited=1').get(orderId);const n=Number(value);if(!p || !/^\d+$/.test(String(value)) || !Number.isSafeInteger(n) || n<0 || n>1000000 || !note.trim() || note.length>200)throw new Error('Tagihan harus lunas; biaya 0–1.000.000 IDR dan catatan mutasi wajib.');db.transaction(()=>{db.prepare('INSERT INTO payment_fee_overrides(order_id,fee,note,admin_id,record_key) VALUES(?,?,?,?,?) ON CONFLICT(order_id) DO UPDATE SET fee=excluded.fee,note=excluded.note,admin_id=excluded.admin_id,created_at=CURRENT_TIMESTAMP').run(orderId,n,note.trim(),id,randomUUID());audit(id,'Catat biaya gateway '+orderId+': '+n+' IDR');})();}
  function report(id,period){admin(id);if(!['day','month'].includes(period))throw new Error('Periode tidak valid.');const format=period==='day'?'%Y-%m-%d':'%Y-%m',key=new Date(now()+7*3600000).toISOString().slice(0,period==='day'?10:7),r=db.prepare(`SELECT COUNT(*) orders,COALESCE(SUM(amount),0) gross,COALESCE(SUM(discount_amount),0) discount,COALESCE(SUM(CASE WHEN refunded=1 THEN amount ELSE 0 END),0) refunds,COALESCE(SUM(CASE WHEN refunded=0 THEN amount ELSE 0 END),0) net,COALESCE(SUM(CASE WHEN refunded=0 AND provider_amount IS NOT NULL THEN provider_amount ELSE 0 END),0) provider,COALESCE(SUM(CASE WHEN refunded=0 AND provider_amount IS NULL THEN 1 ELSE 0 END),0) unknown_provider FROM orders WHERE is_owner_test=0 AND strftime('${format}',created_at,'+7 hours')=?`).get(key),f=db.prepare(`SELECT COALESCE(SUM(COALESCE(o.fee,t.fee_merchant,0)),0) gateway,COALESCE(SUM(CASE WHEN o.fee IS NULL AND t.fee_merchant IS NULL THEN 1 ELSE 0 END),0) unknown_gateway FROM topups t LEFT JOIN payment_fee_overrides o ON o.order_id=t.order_id WHERE t.credited=1 AND strftime('${format}',COALESCE(t.paid_at,t.created_at),'+7 hours')=?`).get(key);const exists=db.prepare("SELECT 1 FROM sqlite_master WHERE type='table' AND name='manual_product_orders'").get(),digital=exists?db.prepare(`SELECT COUNT(*) orders,COALESCE(SUM(amount),0) gross,COALESCE(SUM(CASE WHEN state='refunded' THEN amount ELSE 0 END),0) refunds,COALESCE(SUM(CASE WHEN state<>'refunded' THEN amount ELSE 0 END),0) net FROM manual_product_orders WHERE state IN ('pending','completed','refunded') AND strftime('${format}',created_at,'+7 hours')=?`).get(key):{orders:0,gross:0,refunds:0,net:0};return {...r,...f,key,otp_orders:r.orders,otp_net:r.net,digital_orders:digital.orders,digital_net:digital.net,digital_refunds:digital.refunds,orders:r.orders+digital.orders,gross:r.gross+digital.gross,refunds:r.refunds+digital.refunds,net:r.net+digital.net,estimate:r.net+digital.net-r.provider-f.gateway};}
  function reportCSV(id,period){const r=report(id,period);return Buffer.from('\ufeff'+['periode_wib','pesanan','penjualan_setelah_diskon','diskon','refund','penjualan_net','provider_tercatat','gateway_tercatat','selisih_sementara','pesanan_biaya_provider_belum_tercatat','tagihan_biaya_gateway_belum_tercatat','pesanan_otp','penjualan_net_otp','pesanan_produk_digital','penjualan_net_produk_digital','refund_produk_digital'].map(csvCell).join(',')+'\r\n'+[r.key,r.orders,r.gross,r.discount,r.refunds,r.net,r.provider,r.gateway,r.estimate,r.unknown_provider,r.unknown_gateway,r.otp_orders,r.otp_net,r.digital_orders,r.digital_net,r.digital_refunds].map(csvCell).join(',')+'\r\n','utf8');}
  function auditList(id,page=0){admin(id);const sources=["SELECT created_at,admin_id,action,'toko' source FROM shop_admin_audit", "SELECT created_at,admin_id,action,'operasional' source FROM store_feature_audit", "SELECT created_at,admin_id,'Tambah saldo '||amount||' IDR ke '||discord_id||' ('||note||')' action,'saldo' source FROM manual_balance_credits", "SELECT created_at,admin_id,action||' pembayaran '||invoice_id||' ('||note||')' action,'resolusi' source FROM admin_resolutions", "SELECT created_at,admin_id,setting action,'pengaturan' source FROM admin_settings_audit", "SELECT created_at,owner_id admin_id,action||' admin '||discord_id action,'akses admin' source FROM store_staff_audit", "SELECT created_at,admin_id,action||' server '||guild_id action,'akses server' source FROM discord_server_access_audit"];return pages('SELECT * FROM ('+sources.join(' UNION ALL ')+') ORDER BY created_at DESC,source,action',[],page);}
  function feeHistory(id,page=0){
    admin(id);
    const summary=db.prepare('SELECT COUNT(*) count,COALESCE(SUM(fee),0) total FROM payment_fee_overrides').get(),pages=Math.max(1,Math.ceil(summary.count/2));
    page=Math.min(Math.max(Number.isSafeInteger(page)?page:0,0),pages-1);
    const rows=db.prepare('SELECT f.record_key record_id,f.*,t.gateway,t.amount,t.purpose FROM payment_fee_overrides f LEFT JOIN topups t ON t.order_id=f.order_id ORDER BY f.created_at DESC,f.order_id ASC LIMIT 2 OFFSET ?').all(page*2);
    return {...summary,page,pages,rows};
  }
  function feeRecord(id,recordId){admin(id);const r=db.prepare('SELECT record_key record_id,* FROM payment_fee_overrides WHERE record_key=?').get(String(recordId));if(!r)throw Error('Catatan biaya tidak ditemukan.');return r;}
  function removeFee(id,recordId){admin(id);return db.transaction(()=>{const r=feeRecord(id,recordId);db.prepare('DELETE FROM payment_fee_overrides WHERE record_key=?').run(r.record_id);audit(id,'Hapus koreksi biaya gateway '+r.order_id+': '+r.fee+' IDR');return r;})();}
  return {audit,coupons,ticket,getTicket,replyTicket,tickets,backup,backupStatus,backupToggle,downloadBackup,reconcile,notifyTickets,subscribe,stock,fee,feeHistory,feeRecord,removeFee,report,reportCSV,auditList};
}
function createShopToolsHandler({discord,tools,staff,commerce}){
  const {ActionRowBuilder,ButtonBuilder,ButtonStyle,ModalBuilder,TextInputBuilder,TextInputStyle}=discord;
  const row=xs=>new ActionRowBuilder().addComponents(...xs.map(([id,label])=>new ButtonBuilder().setCustomId(id).setLabel(String(label).slice(0,80)).setStyle(ButtonStyle.Secondary)));
  const money=n=>Number(n || 0).toLocaleString('id-ID')+' IDR';
  const nav=(prefix,r,back)=>{const n=row([[prefix+(r.page-1),'Sebelumnya'],[prefix+(r.page+1),'Berikutnya'],[back,'Kembali']]);n.components[0].setDisabled(r.page===0);n.components[1].setDisabled(r.page===r.pages-1);return n;};
  const form=(id,title,fields)=>{const m=new ModalBuilder().setCustomId(id).setTitle(title);for(const [key,label,max,required=true,paragraph=false,value] of fields){const f=new TextInputBuilder().setCustomId(key).setLabel(label).setRequired(required).setMaxLength(max).setStyle(paragraph?TextInputStyle.Paragraph:TextInputStyle.Short);if(value)f.setValue(value);m.addComponents(new ActionRowBuilder().addComponents(f));}return m;};
  return async i=>{const id=String(i.customId || ''),isAdmin=id.startsWith('admin_tools_');if(!isAdmin && !id.startsWith('tool_'))return false;if(isAdmin && !staff.isAdmin(i.user.id)){await i.reply({ephemeral:true,content:'Akses ditolak.'});return true;}
    try{
      if(id==='tool_ticket_new' || id.startsWith('tool_ticket_new:')){await i.showModal(form('tool_ticket_create','Tiket Bantuan',[['order','ID pesanan (kosong jika umum)',60,false,false,id.split(':')[1]],['body','Jelaskan kendala',1000,true,true]]));return true;}
      if(/^(tool_ticket_reply:|admin_tools_ticket_reply:|admin_tools_ticket_close:)/.test(id)){const ticket=id.split(':')[1];tools.getTicket(ticket,i.user.id,isAdmin);await i.showModal(form(id.replace('reply','save').replace('close','saveclose'),'Balasan Tiket',[['body','Balasan / alasan penutupan',1000,true,true]]));return true;}
      if(id.startsWith('tool_coupon:')){commerce.checkout(i.user.id,id.split(':')[1]);await i.showModal(form('tool_coupon_apply:'+id.split(':')[1],'Gunakan Voucher',[['code','Kode voucher',20]]));return true;}
      if(id==='admin_tools_coupon_new'){await i.showModal(form('admin_tools_coupon_create','Buat Voucher',[['code','Kode (huruf/angka/-/_)',20],['discount','Diskon rupiah tanpa titik',7],['minimum','Minimum pembelian rupiah',7],['expiry','Kedaluwarsa YYYY-MM-DD (WIB)',10],['limit','Batas pemakaian total (1x per pembeli)',7]]));return true;}
      if(id==='admin_tools_fee'){await i.showModal(form('admin_tools_fee_save','Biaya Gateway Aktual',[['invoice','ID tagihan lunas',100],['fee','Biaya merchant rupiah (0 jika bebas)',7],['note','Catatan dari laporan/mutasi gateway',200]]));return true;}
      if(id.startsWith('admin_tools_fee_edit:')){const f=tools.feeRecord(i.user.id,id.split(':')[1]);await i.showModal(form('admin_tools_fee_update:'+f.record_id,'Ubah Catatan Biaya Gateway',[['fee','Biaya merchant rupiah',7,true,false,String(f.fee)],['note','Catatan mutasi gateway',200,true,true,f.note]]));return true;}
      await i.deferReply({ephemeral:true});const user=i.user.id;
      if(id==='tool_ticket_create'){const t=tools.ticket(i.id,user,i.fields.getTextInputValue('order'),i.fields.getTextInputValue('body'));await i.editReply({content:`🎫 Tiket ${t.id} tersimpan. Admin akan memeriksa kendala Anda.`,components:[row([['tool_ticket:'+t.id,'Buka Tiket']])]});tools.notifyTickets().catch(()=>{});}
      else if(id.startsWith('tool_ticket_save:') || /^admin_tools_ticket_save(close)?:/.test(id)){tools.replyTicket(id.split(':')[1],user,i.fields.getTextInputValue('body'),isAdmin,id.startsWith('admin_tools_ticket_saveclose:'));await i.editReply({content:'Balasan tersimpan.',components:[row([[(isAdmin?'admin_tools_ticket:':'tool_ticket:')+id.split(':')[1],'Buka Tiket']])]});tools.notifyTickets().catch(()=>{});}
      else if(id.startsWith('tool_tickets:') || id.startsWith('admin_tools_tickets:')){const r=tools.tickets(user,Number(id.split(':')[1]),isAdmin),components=[];if(r.rows.length)components.push(row(r.rows.map(t=>[(isAdmin?'admin_tools_ticket:':'tool_ticket:')+t.id,`${t.id} • ${t.status} • ${t.order_ref || 'umum'}`])));components.push(nav(isAdmin?'admin_tools_tickets:':'tool_tickets:',r,isAdmin?'admin_balance_menu':'shop_help'));await i.editReply({content:`**🎫 ${isAdmin?'Tiket Terbuka':'Tiket Saya'}**\n${r.count} tiket • halaman ${r.page+1}/${r.pages}`,components});}
      else if(id.startsWith('tool_ticket:') || id.startsWith('admin_tools_ticket:')){const t=tools.getTicket(id.split(':')[1],user,isAdmin),choices=[];if(t.status==='open'){choices.push([(isAdmin?'admin_tools_ticket_reply:':'tool_ticket_reply:')+t.id,'Balas']);if(isAdmin)choices.push(['admin_tools_ticket_close:'+t.id,'Tutup Tiket']);}choices.push([isAdmin?'admin_tools_tickets:0':'tool_tickets:0','Kembali']);await i.editReply({content:`🎫 **Tiket ${t.id}**\nPembeli: ${buyerLabel(t.discord_id)}\nPesanan: ${t.order_ref || 'Umum'} • ${t.status}\n\n${t.messages.map(m=>`**${m.role==='admin'?'Admin':'Pembeli'}:** ${m.body}`).join('\n\n').slice(-1300)}\n\nMenampilkan 5 pesan terakhir.`,allowedMentions:{parse:[]},components:[row(choices)]});}
      else if(id.startsWith('tool_stock:')){const enabled=tools.subscribe(user,id.split(':')[1]);await i.editReply({content:enabled?'🔔 Notifikasi stok aktif. Pemberitahuan dikirim lewat DM saat stok tersedia.':'Notifikasi stok dimatikan.',components:[row([['favorite_detail:'+id.split(':')[1],'Kembali']])]});}
      else if(id.startsWith('tool_coupon_apply:')){const token=id.split(':')[1],q=commerce.applyCoupon(user,token,i.fields.getTextInputValue('code'));await i.editReply({content:`🎟️ Voucher **${q.coupon}** diterapkan.\nHarga awal: ${money(q.originalAmount)}\nDiskon: ${money(q.discount)}\nHarga bayar: **${money(q.amount)}**\nBelum memotong saldo. Voucher divalidasi lagi saat pembayaran.`,components:[row([['confirm_buy:'+token,'Bayar Pakai Saldo'],['qris_buy:'+token,'Bayar Langsung QRIS'],['shop_products','Pilih Ulang']])]});}
      else if(id==='admin_tools_coupon_create'){const v={};for(const k of ['code','discount','minimum','expiry','limit'])v[k]=i.fields.getTextInputValue(k).trim();const c=tools.coupons.create(user,v);await i.editReply({content:`Voucher ${c} dibuat. Setiap pembeli maksimal 1 kali; diskon tidak boleh melebihi margin layanan.`,components:[row([['admin_tools_coupons:0','Daftar Voucher']])]});}
      else if(id.startsWith('admin_tools_coupons:') || id.startsWith('admin_tools_coupon_toggle:')){if(id.startsWith('admin_tools_coupon_toggle:'))tools.coupons.toggle(user,id.split(':')[1]);const r=tools.coupons.list(user,id.startsWith('admin_tools_coupons:')?Number(id.split(':')[1]):0),components=[];if(r.rows.length)components.push(row(r.rows.map(v=>['admin_tools_coupon_toggle:'+v.code,`${v.code} • -${money(v.discount)} • ${v.enabled?'aktif':'nonaktif'}`])));components.push(nav('admin_tools_coupons:',r,'admin_catalog_promo'));components.push(row([['admin_tools_coupon_new','Buat Voucher']]));await i.editReply({content:`**🎟️ Voucher** • halaman ${r.page+1}/${r.pages}\n${r.rows.map(v=>`${v.code}: minimum ${money(v.minimum)}, batas ${v.max_uses} kali, berlaku sampai ${new Date(v.expires_at+7*3600000).toISOString().slice(0,10)} WIB`).join('\n') || 'Belum ada.'}\nTekan voucher untuk aktif/nonaktif.`,components});}
      else if(id==='admin_tools_backup' || id==='admin_tools_backup_run' || id==='admin_tools_backup_toggle' || id==='admin_tools_backup_download'){if(id==='admin_tools_backup_run')await tools.backup(user,true);if(id==='admin_tools_backup_toggle')tools.backupToggle(user);const s=tools.backupStatus(user);if(id==='admin_tools_backup_download'){await i.editReply({content:'Backup database pribadi owner. Simpan dengan aman.',files:[{attachment:tools.downloadBackup(user),name:'shop-backup.db'}]});return true;}await i.editReply({content:`**💾 Backup Database (Owner)**\nBackup harian WIB: ${s.enabled?'AKTIF':'NONAKTIF'}\nTerakhir: ${s.last}\n${s.error}\nMenyimpan 7 salinan terbaru. Salinan di volume yang sama tidak melindungi dari penghapusan volume; simpan unduhan terpisah / aktifkan backup Railway.`,components:[row([['admin_tools_backup_run','Backup Sekarang'],['admin_tools_backup_download','Unduh Backup'],['admin_tools_backup_toggle',s.enabled?'Matikan Jadwal':'Aktifkan Jadwal'],['admin_system_data','Kembali']])]});}
      else if(id==='admin_tools_reconcile'){await tools.reconcile();tools.audit(user,'Periksa ulang topup tertunda');await i.editReply({content:'Pemeriksaan batch maksimal 5 topup selesai. Pembayaran yang belum pasti tidak diulang atau dianggap gagal. Pemeriksaan otomatis berjalan setiap 30 detik.',components:[row([['admin_payment_checks','Kembali']])]});}
      else if(id==='admin_tools_fee_save'){tools.fee(user,i.fields.getTextInputValue('invoice').trim(),i.fields.getTextInputValue('fee').trim(),i.fields.getTextInputValue('note'));await i.editReply({content:'Biaya gateway aktual tersimpan untuk laporan.',components:[row([['admin_tools_fees:0','Riwayat Biaya Gateway'],['admin_reports_menu','Laporan']])]});}
      else if(id.startsWith('admin_tools_fees:')){
        const r=tools.feeHistory(user,Number(id.split(':')[1])),escape=v=>String(v??'-').replace(/[\\`*_~|<>]/g,'\\$&');
        const entries=r.rows.map(f=>`Invoice: ${escape(f.order_id).slice(0,180)}\nGateway: ${escape(f.gateway)} • Nilai tagihan: ${money(f.amount)}\nBiaya merchant: **${money(f.fee)}**\nCatatan: ${escape(f.note).slice(0,320)}\nDicatat oleh: ${escape(f.admin_id)} • ${escape(f.created_at)} UTC`);
        await i.editReply({content:`**Riwayat Biaya Gateway**\n${r.count} catatan • Total biaya tercatat: ${money(r.total)}\nHalaman ${r.page+1}/${r.pages}\n\n${entries.length?entries.join('\n\n'):'Belum ada biaya gateway yang dicatat manual.'}\n\nMenampilkan catatan manual terbaru per invoice. Biaya otomatis dari gateway tetap masuk laporan periode.`,allowedMentions:{parse:[]},components:[...(r.rows.length?[row(r.rows.map((f,n)=>['admin_tools_fee_detail:'+f.record_id,'Kelola Catatan '+(r.page*2+n+1)]))]:[]),nav('admin_tools_fees:',r,'admin_reports_menu')]});
      }
      else if(id.startsWith('admin_tools_fee_update:')){const f=tools.feeRecord(user,id.split(':')[1]);tools.fee(user,f.order_id,i.fields.getTextInputValue('fee').trim(),i.fields.getTextInputValue('note'));await i.editReply({content:'✅ Catatan biaya diperbarui.',components:[row([['admin_tools_fees:0','Riwayat Biaya Gateway']])]});}
      else if(id.startsWith('admin_tools_fee_detail:')||id.startsWith('admin_tools_fee_delete_confirm:')){const f=tools.feeRecord(user,id.split(':')[1]),confirm=id.startsWith('admin_tools_fee_delete_confirm:');await i.editReply({content:`**${confirm?'Hapus Catatan Biaya?':'Kelola Catatan Biaya'}**\nInvoice: ${f.order_id}\nBiaya: ${money(f.fee)}\nCatatan: ${f.note}\n\n${confirm?'Koreksi manual akan dihapus. Laporan kembali memakai biaya dari gateway jika tersedia; jika tidak, ditandai belum tercatat. Invoice, saldo, dan transaksi tidak dihapus.':'Pilih ubah atau hapus koreksi biaya manual.'}`,allowedMentions:{parse:[]},components:[row(confirm?[['admin_tools_fee_delete:'+f.record_id,'Ya, Hapus Catatan'],['admin_tools_fee_detail:'+f.record_id,'Batal']]:[['admin_tools_fee_edit:'+f.record_id,'Ubah Catatan'],['admin_tools_fee_delete_confirm:'+f.record_id,'Hapus Catatan']]),row([['admin_tools_fees:0','Kembali']])]});}
      else if(id.startsWith('admin_tools_fee_delete:')){tools.removeFee(user,id.split(':')[1]);await i.editReply({content:'✅ Koreksi biaya manual dihapus. Invoice dan transaksi tetap tersimpan.',components:[row([['admin_tools_fees:0','Riwayat Biaya Gateway']])]});}
      else if(/^admin_tools_(report|csv):/.test(id)){const period=id.split(':')[1],r=tools.report(user,period);if(id.startsWith('admin_tools_csv:')){await i.editReply({content:`Ringkasan ${r.key} (WIB). Selisih masih sementara jika biaya belum lengkap; hosting/biaya lain tidak termasuk.`,files:[{attachment:tools.reportCSV(user,period),name:'laporan-'+r.key+'.csv'}]});return true;}await i.editReply({content:`**📊 Laporan Penjualan ${r.key} (WIB)**\nPesanan: ${r.orders}\nOTP: ${r.otp_orders} • net ${money(r.otp_net)}\nProduk digital: ${r.digital_orders} • net ${money(r.digital_net)}\nPenjualan setelah diskon: ${money(r.gross)}\nDiskon voucher: ${money(r.discount)}\nRefund: ${money(r.refunds)}\nPenjualan net: ${money(r.net)}\nProvider tercatat: ${money(r.provider)}\nGateway tercatat: ${money(r.gateway)}\n**Selisih sementara: ${money(r.estimate)}**\nBiaya provider belum tercatat: ${r.unknown_provider} pesanan\nBiaya gateway belum tercatat: ${r.unknown_gateway} tagihan\n\nPesanan produk digital yang sudah dibayar (menunggu admin, selesai, atau refund) dihitung sekali; invoice belum dibayar tidak masuk. Belum termasuk modal produk digital, hosting/biaya lain. Biaya gateway semua topup/pembelian pada periode pembayaran; bukan perhitungan laba akuntansi. Refund menurut periode order, data pembayaran lama memakai tanggal tagihan.`,components:[row([['admin_tools_csv:'+period,'Ekspor CSV'],['admin_reports_menu','Kembali']])]});}
      else if(id.startsWith('admin_tools_audit:')){const r=tools.auditList(user,Number(id.split(':')[1]));await i.editReply({content:`**📜 Aktivitas Admin** • halaman ${r.page+1}/${r.pages}\n\n${r.rows.map(a=>`${a.created_at} UTC • ${a.admin_id}\n${a.source}: ${String(a.action).slice(0,180)}`).join('\n\n') || 'Belum ada.'}`,allowedMentions:{parse:[]},components:[nav('admin_tools_audit:',r,'admin_system_menu')]});}
      else throw new Error('Menu tidak dikenal.');return true;
    }catch(e){const p={content:e.message,allowedMentions:{parse:[]}};if(i.deferred || i.replied)await i.editReply(p);else await i.reply({ephemeral:true,...p});return true;}
  };
}
module.exports={csvCell,createShopTools,createShopToolsHandler};
