function createShopHealth({diagnostics,db,staff,payments,products,sendDM,inspectChannel,language=()=>'id',env=process.env,now=Date.now}){
  db.exec(`CREATE TABLE IF NOT EXISTS shop_health_settings(key TEXT PRIMARY KEY,value TEXT NOT NULL);
    CREATE TABLE IF NOT EXISTS owner_incident_alerts(scope TEXT NOT NULL,owner_id TEXT NOT NULL,seen_ms INTEGER NOT NULL DEFAULT 0,total_count INTEGER NOT NULL DEFAULT 0,sent_ms INTEGER NOT NULL DEFAULT 0,attempt_ms INTEGER NOT NULL DEFAULT 0,PRIMARY KEY(scope,owner_id));
    CREATE TABLE IF NOT EXISTS invoice_reminders(order_id TEXT PRIMARY KEY,sent_ms INTEGER NOT NULL DEFAULT 0,checked_ms INTEGER NOT NULL DEFAULT 0);
    CREATE TABLE IF NOT EXISTS overdue_notifications(kind TEXT NOT NULL,ref TEXT NOT NULL,admin_id TEXT NOT NULL,sent_at INTEGER NOT NULL,PRIMARY KEY(kind,ref,admin_id));
    CREATE TABLE IF NOT EXISTS gateway_refund_reviews(id INTEGER PRIMARY KEY,order_id TEXT NOT NULL UNIQUE,observed_status TEXT NOT NULL,observed_amount INTEGER,observed_ref TEXT,revision INTEGER NOT NULL DEFAULT 1,state TEXT NOT NULL DEFAULT 'open',note TEXT,admin_id TEXT,resolved_ms INTEGER);
    CREATE TABLE IF NOT EXISTS gateway_callback_monitor(order_id TEXT PRIMARY KEY,checked_ms INTEGER NOT NULL DEFAULT 0,state TEXT NOT NULL DEFAULT 'waiting');`);
  const admin=id=>{if(!staff.isAdmin(id))throw Error('Akses ditolak.');};
  const read=(k,f)=>db.prepare('SELECT value FROM shop_health_settings WHERE key=?').get(k)?.value??f;
  const write=(k,v)=>db.prepare('INSERT INTO shop_health_settings VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value').run(k,String(v));
  function settings(user){admin(user);return {minutes:Number(read('minutes','15')),enabled:read('enabled','1')==='1'};}
  function configure(user,value){admin(user);if(!/^\d+$/.test(String(value))||Number(value)<5||Number(value)>1440)throw Error('Batas keterlambatan 5–1440 menit, tanpa titik.');write('minutes',value);}
  function toggle(user){const s=settings(user);write('enabled',s.enabled?'0':'1');}
  function alertSettings(user){admin(user);return {enabled:read('incident_enabled','1')==='1'};}
  function toggleAlerts(user){if(!staff.isOwner?.(user))throw Error('Hanya owner boleh mengatur peringatan gangguan.');write('incident_enabled',read('incident_enabled','1')==='1'?'0':'1');}
  let alerting=false;
  async function alertOwner(){if(alerting||!sendDM||read('incident_enabled','1')!=='1'||!db.prepare("SELECT 1 FROM sqlite_master WHERE name='bot_diagnostics'").get())return;alerting=true;
    try{const groups=db.prepare("SELECT scope,MAX(seen_at) seen_ms,SUM(count) total_count FROM bot_diagnostics WHERE seen_at>? AND scope IN ('payment','provider','webhook','product_dm','product_poll') GROUP BY scope ORDER BY seen_ms DESC LIMIT 5").all(now()-24*3600000);
      for(const owner of staff.ids().filter(id=>staff.isOwner?.(id)))for(const g of groups){if(!staff.isOwner(owner))break;const old=db.prepare('SELECT * FROM owner_incident_alerts WHERE scope=? AND owner_id=?').get(g.scope,owner);
        if(old&&(g.seen_ms<=old.seen_ms&&g.total_count===old.total_count||old.sent_ms&&now()-old.sent_ms<15*60000||old.attempt_ms&&now()-old.attempt_ms<60000))continue;
        db.prepare('INSERT INTO owner_incident_alerts(scope,owner_id,attempt_ms) VALUES(?,?,?) ON CONFLICT(scope,owner_id) DO UPDATE SET attempt_ms=excluded.attempt_ms').run(g.scope,owner,now());
        try{const en=language(owner)==='en';await sendDM(owner,(en?'⚠️ Store incident':'⚠️ Gangguan toko')+'\n'+g.scope+'\n'+(en?'Latest event: ':'Kejadian terakhir: ')+'<t:'+Math.floor(g.seen_ms/1000)+':R>\n'+(en?'Open /admin → System → Data & Maintenance → Store Readiness → Incident Log. No automatic charge or refund is performed.':'Buka /admin → Sistem → Data & Pemeliharaan → Kesiapan Toko → Catatan Gangguan. Tidak ada pembayaran atau refund otomatis dari peringatan ini.'));
          db.prepare('UPDATE owner_incident_alerts SET seen_ms=?,total_count=?,sent_ms=? WHERE scope=? AND owner_id=?').run(g.seen_ms,g.total_count,now(),g.scope,owner);
        }catch{/* Failed owner DMs retry with a one-minute backoff. */}
      }
    }finally{alerting=false;}}
  const lateQuery=`SELECT 'digital_pending' kind,id ref,discord_id,updated_at since FROM manual_product_orders WHERE state='pending'
    UNION ALL SELECT 'digital_dm',id,discord_id,updated_at FROM manual_product_orders WHERE state IN ('completed','refunded') AND notified=0
    UNION ALL SELECT 'otp_review',invoice_id,discord_id,created_at FROM direct_purchases WHERE state IN ('review','processing')
    UNION ALL SELECT 'paid_pending',m.id,m.discord_id,COALESCE(p.paid_at,m.updated_at) FROM manual_product_orders m JOIN topups p ON p.order_id=m.invoice_id WHERE m.state='awaiting_payment' AND p.credited=1`;
  function overdueQuery(){return 'SELECT * FROM ('+lateQuery+") WHERE julianday(since)<=julianday(?,'unixepoch')-?/1440.0";}
  function page(query,args,requested=0){const count=db.prepare('SELECT COUNT(*) n FROM ('+query+')').get(...args).n,pages=Math.max(1,Math.ceil(count/5)),p=Math.min(Math.max(Number.isSafeInteger(requested)?requested:0,0),pages-1);return {count,pages,page:p,rows:db.prepare(query+' ORDER BY kind,ref LIMIT 5 OFFSET ?').all(...args,p*5)};}
  function overdue(user,p=0){const s=settings(user);return {...page(overdueQuery(),[now()/1000,s.minutes],p),...s};}
  let reminding=false;
  async function remindInvoices(){if(reminding||!sendDM||!db.prepare('PRAGMA table_info(topups)').all().some(c=>c.name==='expires_ms'))return;reminding=true;
    try{const rows=db.prepare("SELECT p.* FROM topups p LEFT JOIN invoice_reminders r ON r.order_id=p.order_id WHERE p.credited=0 AND p.status='pending' AND p.qr_url IS NOT NULL AND p.expires_ms>? AND p.expires_ms<=? AND COALESCE(r.sent_ms,0)=0 AND COALESCE(r.checked_ms,0)<=? ORDER BY p.expires_ms LIMIT 5").all(now(),now()+5*60000,now()-60000);
      for(const p of rows){db.prepare('INSERT INTO invoice_reminders(order_id,checked_ms) VALUES(?,?) ON CONFLICT(order_id) DO UPDATE SET checked_ms=excluded.checked_ms').run(p.order_id,now());
        try{await payments.refresh(p.order_id,p.discord_id);const current=payments.get(p.order_id,p.discord_id);if(!current||current.credited||current.status!=='pending'||!current.qr_url||current.expires_ms<=now())continue;
          await sendDM(p.discord_id,language(p.discord_id)==='en'?'⏰ QRIS invoice expires soon\nInvoice: '+p.order_id+'\nInvoice deadline: <t:'+Math.floor(current.expires_ms/1000)+':F>\nIf unpaid, use the QR on the same invoice. If already paid, check Orders → Invoice in the store server; do not pay again. This reminder does not create another invoice.':'⏰ Invoice QRIS segera kedaluwarsa\nInvoice: '+p.order_id+'\nBatas tagihan: <t:'+Math.floor(current.expires_ms/1000)+':F>\nJika belum dibayar, gunakan QR pada tagihan yang sama. Jika sudah dibayar, cek status melalui Pesanan → Invoice di server toko; jangan membayar ulang. Pengingat ini tidak membuat tagihan baru.');
          db.prepare('UPDATE invoice_reminders SET sent_ms=? WHERE order_id=?').run(now(),p.order_id);
        }catch{diagnostics?.record('payment','FAILED',p.order_id);}
      }
    }finally{reminding=false;}
  }
  let notifying=false;
  async function poll(){await monitorCallbacks();await alertOwner();await remindInvoices();if(notifying||!sendDM||read('enabled','1')!=='1')return;notifying=true;
    try {for(const id of staff.ids().filter(x=>staff.isAdmin(x))){const query='SELECT q.* FROM ('+overdueQuery()+') q WHERE NOT EXISTS(SELECT 1 FROM overdue_notifications n WHERE n.kind=q.kind AND n.ref=q.ref AND n.admin_id=?) ORDER BY q.since LIMIT 5';
      for(const o of db.prepare(query).all(now()/1000,Number(read('minutes','15')),id)){
        if(!staff.isAdmin(id))break;
        try{await sendDM(id,`⚠️ Pesanan perlu ditangani\n${label(o.kind)}\nID: ${o.ref}\nPembeli: ${o.discord_id}\nBuka /admin → Pembayaran → Pemeriksaan → Pesanan Terlambat. Tidak ada pemotongan saldo atau refund otomatis dari peringatan ini.`);db.prepare('INSERT OR IGNORE INTO overdue_notifications VALUES(?,?,?,?)').run(o.kind,o.ref,id,now());}catch{}
      }
    }}finally{notifying=false;}
  }
  let findingsQuery=`SELECT 'wallet' kind,discord_id ref,'Saldo negatif' reason FROM users WHERE balance<0
    UNION ALL SELECT 'digital',o.id,'Pesanan QRIS tidak cocok dengan pembayaran tercatat' FROM manual_product_orders o
      LEFT JOIN topups p ON p.order_id=o.invoice_id WHERE o.payment_method='qris' AND o.state IN ('pending','completed','refunded')
      AND (p.order_id IS NULL OR p.credited<>1 OR p.discord_id<>o.discord_id OR p.amount<>o.amount OR p.purpose<>'purchase')
    UNION ALL SELECT 'digital',o.id,'Pembayaran lunas, pesanan belum diproses' FROM manual_product_orders o JOIN topups p ON p.order_id=o.invoice_id WHERE o.state='awaiting_payment' AND p.credited=1
    UNION ALL SELECT 'invoice',p.order_id,'Pembayaran pembelian tidak terhubung ke pesanan' FROM topups p WHERE p.purpose='purchase' AND p.credited=1
      AND NOT EXISTS(SELECT 1 FROM manual_product_orders m WHERE m.invoice_id=p.order_id) AND NOT EXISTS(SELECT 1 FROM direct_purchases d WHERE d.invoice_id=p.order_id)
    UNION ALL SELECT 'otp',d.invoice_id,'Pesanan berhasil tanpa catatan OTP yang cocok' FROM direct_purchases d WHERE d.state='fulfilled' AND NOT EXISTS(SELECT 1 FROM orders o WHERE o.provider_order_id=d.provider_order_id AND o.discord_id=d.discord_id)
    UNION ALL SELECT 'invoice',p.order_id,'Status lunas tetapi belum ditandai terverifikasi' FROM topups p WHERE p.status='settlement' AND p.credited=0
    UNION ALL SELECT 'otp',d.invoice_id,'Pesanan OTP tidak cocok dengan pembayaran tercatat' FROM direct_purchases d LEFT JOIN topups p ON p.order_id=d.invoice_id WHERE d.state IN ('processing','review','fulfilled','refunded') AND (p.order_id IS NULL OR p.credited<>1 OR p.discord_id<>d.discord_id OR p.amount<>d.amount OR p.purpose<>'purchase')
    UNION ALL SELECT 'stock',CAST(s.id AS TEXT),'Data terjual tidak terhubung ke pesanan selesai' FROM manual_product_stock s WHERE s.state='sold' AND NOT EXISTS(SELECT 1 FROM manual_product_orders o WHERE o.id=s.order_id AND o.state='completed')`;
  const topupColumns=db.prepare('PRAGMA table_info(topups)').all().map(c=>c.name);
  const productColumns=db.prepare('PRAGMA table_info(manual_products)').all().map(c=>c.name);
  const stockQuery="SELECT CAST(p.id AS TEXT) ref,'stock_capacity' kind,'Stok jual melebihi data siap kirim' reason,p.quantity sale_stock,(SELECT COUNT(*) FROM manual_product_stock s WHERE s.product_id=p.id AND s.state='available') ready_data FROM manual_products p WHERE p.deleted=0 AND p.enabled=1 AND p.auto_enabled=1 AND p.quantity IS NOT NULL AND p.quantity>(SELECT COUNT(*) FROM manual_product_stock s WHERE s.product_id=p.id AND s.state='available')"+(productColumns.includes('parent_id')?" AND (p.parent_id IS NULL OR EXISTS(SELECT 1 FROM manual_products root WHERE root.id=p.parent_id AND root.deleted=0 AND root.enabled=1))":'');
  function stockIssues(user,p=0){admin(user);return page(stockQuery,[],p);}
  findingsQuery+=' UNION ALL SELECT kind,ref,reason FROM ('+stockQuery+')';
  if(topupColumns.includes('provider_ref')&&topupColumns.includes('gateway'))findingsQuery+=" UNION ALL SELECT 'invoice',order_id,'Pembuatan invoice belum pasti; referensi gateway belum diterima' FROM topups WHERE gateway IN ('tripay','midtrans') AND status='creating' AND provider_ref IS NULL AND credited=0";
  const hasRefunds=['provider_status','external_refund_amount','provider_ref','gateway'].every(c=>topupColumns.includes(c));
  if(hasRefunds)findingsQuery+=" UNION ALL SELECT 'external_refund',p.order_id,'Refund Midtrans terdeteksi; cocokkan dengan saldo/refund toko dan dashboard merchant' FROM topups p WHERE p.gateway='midtrans' AND p.provider_status IN ('refund','partial_refund') AND "+require('./midtrans').refundReviewFilter('p');
  function syncRefunds(){if(!hasRefunds)return;db.exec(`INSERT INTO gateway_refund_reviews(order_id,observed_status,observed_amount,observed_ref)
    SELECT order_id,provider_status,external_refund_amount,provider_ref FROM topups WHERE gateway='midtrans' AND provider_status IN ('refund','partial_refund')
    ON CONFLICT(order_id) DO UPDATE SET observed_status=excluded.observed_status,observed_amount=excluded.observed_amount,observed_ref=excluded.observed_ref,revision=revision+1,state='open',note=NULL,admin_id=NULL,resolved_ms=NULL
    WHERE observed_status IS NOT excluded.observed_status OR observed_amount IS NOT excluded.observed_amount OR observed_ref IS NOT excluded.observed_ref`);}
  function refundRecord(user,id){admin(user);if(!/^[1-9]\d*$/.test(String(id))||!Number.isSafeInteger(Number(id)))throw Error('Catatan refund tidak valid.');syncRefunds();const r=db.prepare('SELECT * FROM gateway_refund_reviews WHERE id=?').get(Number(id));if(!r)throw Error('Catatan refund tidak ditemukan.');return r;}
  function refunds(user,requested=0,closed=false){admin(user);syncRefunds();return {...page("SELECT 'refund' kind,CAST(id AS TEXT) ref,* FROM gateway_refund_reviews WHERE state=?",[closed?'resolved':'open'],requested),closed};}
  function resolveRefund(user,id,revision,note){admin(user);note=String(note||'').trim();if(note.length<10||note.length>500)throw Error('Catatan pencocokan wajib 10–500 karakter.');
    db.exec('SAVEPOINT refund_resolution');try{const r=refundRecord(user,id);if(r.revision!==Number(revision))throw Error('Data refund berubah. Buka catatan terbaru sebelum menyelesaikan.');if(r.state!=='resolved'){
      db.prepare("UPDATE gateway_refund_reviews SET state='resolved',note=?,admin_id=?,resolved_ms=? WHERE id=? AND revision=? AND state='open'").run(note,user,now(),r.id,r.revision);
      if(db.prepare("SELECT 1 FROM sqlite_master WHERE name='shop_admin_audit'").get())db.prepare('INSERT INTO shop_admin_audit(admin_id,action) VALUES(?,?)').run(user,'Cocokkan refund '+r.order_id+' revisi '+r.revision+': '+note);
    }const result=db.prepare('SELECT * FROM gateway_refund_reviews WHERE id=?').get(r.id);db.exec('RELEASE refund_resolution');return result;}catch(e){db.exec('ROLLBACK TO refund_resolution');db.exec('RELEASE refund_resolution');throw e;}}
  const hasMonitor=['verified_callback_ms','status_checked_ms','gateway','created_at'].every(c=>topupColumns.includes(c));
  let monitoring=false;
  async function monitorCallbacks(){if(monitoring||!hasMonitor||!payments.refresh||!payments.get)return;monitoring=true;
    try{
      db.exec("UPDATE gateway_callback_monitor SET state='closed' WHERE EXISTS(SELECT 1 FROM topups p WHERE p.order_id=gateway_callback_monitor.order_id AND (p.verified_callback_ms IS NOT NULL OR p.status NOT IN ('creating','pending') OR p.credited=1))");
      const rows=db.prepare("SELECT p.* FROM topups p LEFT JOIN gateway_callback_monitor m ON m.order_id=p.order_id WHERE p.gateway IN ('tripay','midtrans') AND p.credited=0 AND p.status IN ('creating','pending') AND p.verified_callback_ms IS NULL AND julianday(p.created_at)<=julianday(?,'unixepoch')-15.0/1440 AND COALESCE(m.checked_ms,0)<=? ORDER BY COALESCE(m.checked_ms,0),p.created_at LIMIT 5").all(now()/1000,now()-5*60000);
      for(const p of rows){const old=db.prepare('SELECT state FROM gateway_callback_monitor WHERE order_id=?').get(p.order_id)?.state;
        db.prepare("INSERT INTO gateway_callback_monitor(order_id,checked_ms) VALUES(?,?) ON CONFLICT(order_id) DO UPDATE SET checked_ms=excluded.checked_ms").run(p.order_id,now());let state;
        let uncertain=false;try{if(!p.status_checked_ms||p.status_checked_ms<=now()-5*60000)await payments.refresh(p.order_id,p.discord_id);}catch{uncertain=true;}const current=payments.get(p.order_id,p.discord_id);state=!current||current.credited||current.verified_callback_ms||!['creating','pending'].includes(current.status)?'closed':uncertain?'api_uncertain':'pending_without_callback';
        db.prepare('UPDATE gateway_callback_monitor SET state=? WHERE order_id=?').run(state,p.order_id);
        if(state==='api_uncertain'&&old!==state)diagnostics?.record('webhook','UNCERTAIN',p.order_id);
      }
    }finally{monitoring=false;}}
  function callbackMonitor(user,requested=0){admin(user);if(!hasMonitor)return {count:0,pages:1,page:0,rows:[],available:false};return {...page("SELECT 'callback' kind,p.order_id ref,p.gateway,p.status,p.status_checked_ms,p.verified_callback_ms,m.checked_ms,m.state FROM gateway_callback_monitor m JOIN topups p ON p.order_id=m.order_id WHERE m.state<>'closed' AND p.credited=0 AND p.status IN ('creating','pending') AND p.verified_callback_ms IS NULL",[],requested),available:true};}
  function midtransStatus(user){admin(user);return payments.midtransHealth?.();}
  async function inspectMidtrans(user,id){admin(user);id=String(id||'').trim();if(!/^[a-zA-Z0-9_-]{1,100}$/.test(id))throw Error('Isi ID invoice bot yang valid.');const result=await payments.inspectMidtrans(id);admin(user);return result;}
  function reconcile(user,p=0){admin(user);return page(findingsQuery,[],p);}
  async function readiness(user,guildId,channelId){admin(user);const dbOK=!!db.prepare('SELECT 1 ok').get().ok;
    let channel='Buka dari channel toko pada server tujuan.';if(guildId)try{channel=await inspectChannel(guildId,channelId);}catch{channel='Channel belum dapat diperiksa. Periksa izin bot.';}
    admin(user);
    const automatic=db.prepare(`SELECT COUNT(*) total,SUM(CASE WHEN p.quantity=0 OR NOT EXISTS(SELECT 1 FROM manual_product_stock s WHERE s.product_id=p.id AND s.state='available') THEN 1 ELSE 0 END) unready FROM manual_products p WHERE p.deleted=0 AND p.enabled=1 AND p.auto_enabled=1`).get();
    const issues=reconcile(user).count;let backup='Belum ada hasil tes pemulihan';if(db.prepare("SELECT 1 FROM sqlite_master WHERE name='shop_tools_settings'").get()){const at=db.prepare("SELECT value FROM shop_tools_settings WHERE key='backup_verified_at'").get()?.value;const tested=db.prepare("SELECT value FROM shop_tools_settings WHERE key='backup_verified_file'").get()?.value,current=db.prepare("SELECT value FROM shop_tools_settings WHERE key='backup_last'").get()?.value;if(at)backup=(tested===current?'Backup terbaru lolos tes: ':'Salinan sebelumnya lolos tes: ')+at;}
    return {dbOK,backup,stockMismatch:stockIssues(user).count,gateway:payments.configured?(payments.production?'Produksi — konfigurasi tersedia':'Sandbox / mode uji'):'Belum dikonfigurasi',provider:!!env.SMSCODE_API_TOKEN,webhook:!!(env.SMSCODE_WEBHOOK_URL&&env.SMSCODE_WEBHOOK_SECRET),channel,automatic:Number(automatic.total),unready:Number(automatic.unready||0),issues};
  }
  async function testDM(user){admin(user);await sendDM(user,'✅ Tes DM admin berhasil. Tidak ada pembelian, pemotongan saldo, atau perubahan stok.');}
  async function recoverInvoice(user,invoice,reference){admin(user);invoice=String(invoice||'').trim();reference=String(reference||'').trim();if(!/^[a-zA-Z0-9_-]{1,100}$/.test(invoice)||! /^[a-zA-Z0-9_-]{1,100}$/.test(reference))throw Error('Isi ID invoice dan referensi TriPay yang valid dari dashboard merchant.');
    const p=db.prepare("SELECT * FROM topups WHERE order_id=? AND gateway='tripay'").get(invoice);if(!p)throw Error('Invoice TriPay tidak ditemukan.');
    const updated=await payments.refresh(invoice,p.discord_id,reference);
    if(db.prepare("SELECT 1 FROM sqlite_master WHERE type='table' AND name='manual_product_orders'").get()){
      const order=db.prepare('SELECT id FROM manual_product_orders WHERE invoice_id=? AND discord_id=?').get(invoice,p.discord_id);if(order&&products?.refresh)await products.refresh(p.discord_id,order.id);
    }
    if(db.prepare("SELECT 1 FROM sqlite_master WHERE type='table' AND name='shop_admin_audit'").get())db.prepare('INSERT INTO shop_admin_audit(admin_id,action) VALUES(?,?)').run(user,'Verifikasi referensi TriPay untuk invoice '+invoice);
    return updated;
  }
  return {refunds,refundRecord,resolveRefund,callbackMonitor,monitorCallbacks,midtransStatus,inspectMidtrans,stockIssues,alertSettings,toggleAlerts,alertOwner,remindInvoices,recoverInvoice,errors:user=>{admin(user);return diagnostics?.recent()||[];},settings,configure,toggle,overdue,poll,reconcile,readiness,testDM};
}
const label=k=>({paid_pending:'Pembayaran lunas, pesanan belum diproses',digital_pending:'Produk dibayar, menunggu admin',digital_dm:'Hasil produk / refund belum terkirim ke DM',otp_review:'Pembayaran OTP perlu diperiksa'}[k]||k);
function createHealthHandler({discord,model,staff}){
  const {ActionRowBuilder,ButtonBuilder,ModalBuilder,TextInputBuilder,TextInputStyle}=discord;
  const b=(id,label,style=1)=>new ButtonBuilder().setCustomId(id).setLabel(label.slice(0,80)).setStyle(style),row=(...v)=>new ActionRowBuilder().addComponents(...v);
  return async i=>{const id=String(i.customId||'');if(!id.startsWith('admin_healthcheck'))return false;
    if(!staff.isAdmin(i.user.id)){await i.reply({ephemeral:true,content:'Akses ditolak.'});return true;}
    const user=i.user.id,home=b('admin_home','Menu Awal Admin');
    if(id.startsWith('admin_healthcheck_refund_resolve:')){try{const r=model.refundRecord(user,id.split(':')[1]);if(r.state!=='open')throw Error('Catatan sudah selesai. Buka riwayat refund.');await i.showModal(new ModalBuilder().setCustomId('admin_healthcheck_refund_save:'+r.id+':'+r.revision).setTitle('Selesaikan Pencocokan Refund').addComponents(row(new TextInputBuilder().setCustomId('note').setLabel('Hasil cek dashboard dan saldo/pesanan').setStyle(TextInputStyle.Paragraph).setRequired(true).setMinLength(10).setMaxLength(500))));}catch(e){await i.reply({ephemeral:true,content:String(e.message).slice(0,1500),allowedMentions:{parse:[]}});}return true;}
    if(id==='admin_healthcheck_midtrans_test'){await i.showModal(new ModalBuilder().setCustomId('admin_healthcheck_midtrans_test_save').setTitle('Tes Status Invoice Midtrans').addComponents(row(new TextInputBuilder().setCustomId('invoice').setLabel('ID invoice bot yang sudah ada').setStyle(TextInputStyle.Short).setRequired(true).setMaxLength(100))));return true;}
    if(id==='admin_healthcheck_limit'){const s=model.settings(user);await i.showModal(new ModalBuilder().setCustomId('admin_healthcheck_limit_save').setTitle('Batas Pesanan Terlambat').addComponents(row(new TextInputBuilder().setCustomId('minutes').setLabel('Menit (5–1440)').setStyle(TextInputStyle.Short).setRequired(true).setMaxLength(4).setValue(String(s.minutes)))));return true;}
    if(id==='admin_healthcheck_invoice'){const m=new ModalBuilder().setCustomId('admin_healthcheck_invoice_save').setTitle('Pulihkan Referensi TriPay');for(const [key,label]of [['invoice','ID invoice bot'],['reference','Referensi dari dashboard TriPay']])m.addComponents(row(new TextInputBuilder().setCustomId(key).setLabel(label).setStyle(TextInputStyle.Short).setRequired(true).setMaxLength(100)));await i.showModal(m);return true;}
    await i.deferReply({ephemeral:true});
    try {
      if(id.startsWith('admin_healthcheck_refund_detail:')||id.startsWith('admin_healthcheck_refund_save:')){
        const parts=id.split(':'),r=id.startsWith('admin_healthcheck_refund_save:')?model.resolveRefund(user,parts[1],parts[2],i.fields.getTextInputValue('note')):model.refundRecord(user,parts[1]);
        await i.editReply({content:'**Pencocokan Refund Gateway**\nInvoice: '+r.order_id+'\nStatus gateway: '+r.observed_status+'\nNominal refund: '+(r.observed_amount==null?'Belum diketahui':r.observed_amount+' IDR')+'\nStatus catatan: '+(r.state==='open'?'Perlu diperiksa':'Sudah dicocokkan')+' • revisi '+r.revision+(r.admin_id?'\nAdmin: '+r.admin_id:'')+'\n\nTombol selesai hanya menyimpan catatan hasil pemeriksaan. Tidak mengubah saldo, pembayaran, refund, atau stok. Jika status/nominal refund bertambah, catatan dibuka kembali.',embeds:r.note?[{title:'Catatan Penyelesaian',description:String(r.note).replace(/([\\`*_~|<>\[\]])/g,'\\$1')}]:[],allowedMentions:{parse:[]},components:[...(r.state==='open'?[row(b('admin_healthcheck_refund_resolve:'+r.id,'Tandai Sudah Dicocokkan',3))]:[]),row(b('admin_healthcheck_refunds:'+(r.state==='open'?'open':'resolved')+':0','Kembali'),home)]});
      }else if(id.startsWith('admin_healthcheck_refunds:')){
        const parts=id.split(':'),r=model.refunds(user,Number(parts[2]),parts[1]==='resolved'),prefix='admin_healthcheck_refunds:'+(r.closed?'resolved':'open')+':';
        await i.editReply({content:'**Refund Gateway • '+(r.closed?'Sudah Dicocokkan':'Perlu Diperiksa')+'**\nHalaman '+(r.page+1)+'/'+r.pages+' • '+r.count+' invoice\nSatu catatan per invoice. Tidak membuat transaksi atau mengubah dana.\n\n'+(r.rows.map(x=>'#'+x.id+' • '+x.order_id+'\n'+x.observed_status+' • '+(x.observed_amount==null?'Nominal belum diketahui':x.observed_amount+' IDR')).join('\n\n')||'Belum ada catatan pada daftar ini.'),allowedMentions:{parse:[]},components:[...(r.rows.length?[row(...r.rows.map(x=>b('admin_healthcheck_refund_detail:'+x.id,'Refund #'+x.id,2)))]:[]),row(b(prefix+(r.page-1),'Sebelumnya').setDisabled(!r.page),b(prefix+(r.page+1),'Berikutnya').setDisabled(r.page===r.pages-1),b('admin_healthcheck_refunds:'+(r.closed?'open':'resolved')+':0',r.closed?'Perlu Diperiksa':'Riwayat Selesai')),row(b('admin_healthcheck_reconcile:0','Kembali'),home)]});
      }else if(id.startsWith('admin_healthcheck_callbacks:')){
        const r=model.callbackMonitor(user,Number(id.split(':')[1]));await i.editReply({content:'**Pemantauan Callback**\nHalaman '+(r.page+1)+'/'+r.pages+' • '+r.count+' invoice\nPemeriksaan otomatis invoice berusia 15 menit, maksimal 5 invoice per putaran dengan jeda 5 menit per invoice.\n\n'+(r.rows.map(x=>x.ref+' • '+x.gateway+'\n'+(x.state==='api_uncertain'?'Status API belum dapat dipastikan':'API masih pending; callback belum tercatat')+'\nDiperiksa: <t:'+Math.floor(x.checked_ms/1000)+':R>').join('\n\n')||'Belum ada invoice tertunda yang ditandai pemantauan.')+'\n\nCallback belum tercatat tidak membuktikan webhook rusak. Jangan membayar ulang sebelum status pasti. Membuka/Perbarui menu hanya membaca catatan; pemeriksaan API berjalan pada jadwal bot.',allowedMentions:{parse:[]},components:[row(b('admin_healthcheck_callbacks:'+(r.page-1),'Sebelumnya').setDisabled(!r.page),b('admin_healthcheck_callbacks:'+(r.page+1),'Berikutnya').setDisabled(r.page===r.pages-1),b('admin_healthcheck_callbacks:'+r.page,'Perbarui')),row(b('admin_healthcheck_reconcile:0','Kembali'),home)]});
      }else if(id==='admin_healthcheck_midtrans'||id==='admin_healthcheck_midtrans_test_save'){
        let result='';if(id.endsWith('_save')){const p=await model.inspectMidtrans(user,i.fields.getTextInputValue('invoice'));result='✅ API membaca invoice: '+p.order_id+'\nStatus provider: '+p.status+'\nNominal: '+p.amount+' IDR\n'+(p.expires_ms?'Batas: <t:'+Math.floor(p.expires_ms/1000)+':F>\n':'Batas belum tersedia dari provider.\n');}
        const h=model.midtransStatus(user);if(!h)throw Error('Perbarui payments.js dan midtrans.js bersama shop-health.js.');const time=ms=>ms?'<t:'+Math.floor(ms/1000)+':R>':'Belum ada';
        await i.editReply({content:'**Pemeriksaan Midtrans**\n'+result+'Mode: '+(h.production?'Produksi':'Sandbox')+'\nServer Key: '+(h.configured?'Tersedia':'Belum diisi')+'\nAcquirer: '+h.acquirer+'\nCallback: https://DOMAIN-PUBLIK-BOT'+h.callbackPath+'\nAPI terakhir: '+h.apiCode+' • '+time(h.lastAPI)+'\nCallback bertanda tangan terakhir: '+h.callbackCode+' • '+time(h.lastCallback)+'\n\nTes ini hanya membaca invoice; tidak menambah saldo, mengirim produk, atau membuat pembayaran. Untuk memproses pembayaran gunakan Cek Pembayaran pada invoice terkait. Ganti DOMAIN-PUBLIK-BOT dengan domain HTTPS Railway Anda. Ketersediaan key belum membuktikan QRIS aktif; biaya merchant tetap belum diketahui sampai dicatat.',allowedMentions:{parse:[]},components:[row(b('admin_healthcheck_midtrans_test','Tes Invoice',3),b('admin_healthcheck_midtrans','Perbarui'),b('admin_healthcheck_reconcile:0','Kembali')),row(home)]});
      }else if(id==='admin_healthcheck_invoice_save'){const p=await model.recoverInvoice(user,i.fields.getTextInputValue('invoice'),i.fields.getTextInputValue('reference'));await i.editReply({content:'Referensi diperiksa langsung melalui API TriPay. Status: '+p.status+'. Tidak membuat tagihan baru.',components:[row(b('admin_healthcheck_reconcile:0','Kembali'),home)]});
      }else if(id==='admin_healthcheck_errors'||id==='admin_healthcheck_alerts'){if(id==='admin_healthcheck_alerts')model.toggleAlerts(user);const rows=model.errors(user),alerts=model.alertSettings(user);await i.editReply({content:'**Catatan Gangguan Bot**\nPeringatan ke owner: '+(alerts.enabled?'Aktif':'Nonaktif')+' • maksimal sekali per jenis dalam 15 menit.\nToken, secret dan isi akun tidak disimpan.\n\n'+(rows.map(r=>`${r.scope} • ${r.code} • ${r.count} kali\nReferensi: ${r.ref||'-'} • <t:${Math.floor(r.seen_at/1000)}:R>`).join('\n\n')||'Belum ada gangguan tercatat.'),allowedMentions:{parse:[]},components:[row(b('admin_healthcheck_errors','Perbarui'),b('admin_healthcheck','Kembali'),home),...(staff.isOwner?.(user)?[row(b('admin_healthcheck_alerts',alerts.enabled?'Matikan Peringatan Owner':'Aktifkan Peringatan Owner'))]:[])]});
      }else if(id.startsWith('admin_healthcheck_stock:')){const r=model.stockIssues(user,Number(id.split(':')[1]));await i.editReply({content:`**Pemeriksaan Stok Otomatis**\nHalaman ${r.page+1}/${r.pages} • ${r.count} produk\n\n`+(r.rows.map(x=>`Produk #${x.ref}: stok jual ${x.sale_stock}, data siap kirim ${x.ready_data}`).join('\n')||'Stok jual tidak melebihi data siap kirim pada produk otomatis aktif.')+'\nTidak mengubah stok atau data. Buka produk untuk memperbaiki konfigurasi.',allowedMentions:{parse:[]},components:[...(r.rows.length?[row(...r.rows.map(x=>b('admin_manual_delivery_data:'+x.ref+':0','Produk #'+x.ref,2)))]:[]),row(b('admin_healthcheck_stock:'+(r.page-1),'Sebelumnya').setDisabled(!r.page),b('admin_healthcheck_stock:'+(r.page+1),'Berikutnya').setDisabled(r.page===r.pages-1),b('admin_healthcheck','Kembali')),row(home)]});
      }else if(id.startsWith('admin_healthcheck_overdue:')||id==='admin_healthcheck_limit_save'||id==='admin_healthcheck_toggle'){
        if(id==='admin_healthcheck_limit_save')model.configure(user,i.fields.getTextInputValue('minutes'));if(id==='admin_healthcheck_toggle')model.toggle(user);
        const r=model.overdue(user,id.includes(':')?Number(id.split(':')[1]):0);
        await i.editReply({content:`**Pesanan Terlambat**\nPeringatan admin: ${r.enabled?'Aktif':'Nonaktif'} • batas ${r.minutes} menit\nHalaman ${r.page+1}/${r.pages} • ${r.count} pesanan\n\n`+r.rows.map(o=>`${label(o.kind)}\nID: ${o.ref}\nPembeli: ${o.discord_id}`).join('\n\n'),allowedMentions:{parse:[]},components:[row(b('admin_healthcheck_overdue:'+(r.page-1),'Sebelumnya').setDisabled(!r.page),b('admin_healthcheck_overdue:'+(r.page+1),'Berikutnya').setDisabled(r.page===r.pages-1),b('admin_healthcheck_overdue:'+r.page,'Perbarui')),row(b('admin_healthcheck_limit','Atur Batas'),b('admin_healthcheck_toggle',r.enabled?'Matikan Peringatan':'Aktifkan Peringatan'),b('admin_payment_requests','Proses Pesanan')),row(b('admin_payment_checks','Kembali'),home)]});
      }else if(id.startsWith('admin_healthcheck_reconcile:')){
        const r=model.reconcile(user,Number(id.split(':')[1]));await i.editReply({content:`**Pencocokan Catatan Transaksi**\nHalaman ${r.page+1}/${r.pages} • ${r.count} temuan\nPemeriksaan lokal; tidak mengubah saldo, status gateway, refund, atau stok.\n\n`+(r.count?r.rows.map(o=>`${o.reason}\nID: ${o.ref}`).join('\n\n'):'Tidak ada ketidakcocokan pada aturan yang diperiksa. Ini bukan rekonstruksi seluruh mutasi saldo atau konfirmasi langsung gateway.'),allowedMentions:{parse:[]},components:[row(b('admin_healthcheck_reconcile:'+(r.page-1),'Sebelumnya').setDisabled(!r.page),b('admin_healthcheck_reconcile:'+(r.page+1),'Berikutnya').setDisabled(r.page===r.pages-1),b('admin_healthcheck_reconcile:'+r.page,'Perbarui')),row(b('admin_healthcheck_invoice','Pulihkan Referensi TriPay'),b('admin_healthcheck_midtrans','Midtrans'),b('admin_healthcheck_refunds:open:0','Refund Gateway'),b('admin_healthcheck_callbacks:0','Pantau Callback')),row(b('admin_payment_issues','Periksa Pesanan'),b('admin_payment_checks','Kembali'),home)]});
      }else{
        let prefix='';if(id==='admin_healthcheck_dm'){await model.testDM(user);prefix='✅ Tes DM terkirim ke Anda.\n\n';}
        const r=await model.readiness(user,i.guildId,i.channelId);await i.editReply({content:prefix+`**Kesiapan Toko**\nBackup: ${r.backup}\nDatabase: ${r.dbOK?'OK':'Perlu diperiksa'}\nQRIS: ${r.gateway}\nAPI SMSCode: ${r.provider?'Konfigurasi tersedia':'Belum diisi'}\nWebhook SMSCode: ${r.webhook?'Konfigurasi tersedia':'Belum lengkap'}\nChannel: ${r.channel}\nProduk otomatis aktif: ${r.automatic} • stok/data belum siap: ${r.unready}\nStok jual melebihi data: ${r.stockMismatch}\nKetidakcocokan transaksi: ${r.issues}\n\nKonfigurasi tersedia belum membuktikan koneksi/API/webhook berhasil. Gunakan tes webhook yang sudah ada dan lakukan transaksi uji sesuai mode gateway. Tes DM admin tidak menjamin DM semua pembeli terbuka.`,components:[row(b('admin_healthcheck','Perbarui'),b('admin_healthcheck_dm','Tes DM Admin',3),b('admin_smscode_webhook_test','Tes Webhook SMSCode')),row(b('admin_healthcheck_errors','Catatan Gangguan'),b('admin_healthcheck_stock:0','Periksa Stok'),b('admin_system_data','Kembali'),home)]});
      }
    }catch(e){await i.editReply({content:id==='admin_healthcheck_dm'?'Tes DM gagal. Aktifkan DM dari anggota server, lalu coba lagi.':String(e.message||'Pemeriksaan gagal.').slice(0,1700),components:[row(b(id.includes('overdue')||id.includes('reconcile')||id.includes('limit')||id.includes('toggle')||id.includes('midtrans')||id.includes('refund')||id.includes('callbacks')?'admin_payment_checks':'admin_system_data','Kembali'),home)],allowedMentions:{parse:[]}});}
    return true;
  };
}
module.exports={createShopHealth,createHealthHandler};
