'use strict';
const fs=require('node:fs/promises'),path=require('node:path');
function bytes(n){if(!Number.isFinite(n)||n<0)return 'Belum tersedia';const units=['B','KB','MB','GB','TB'];let i=0;while(n>=1024&&i<units.length-1){n/=1024;i++;}return n.toFixed(i?1:0)+' '+units[i];}
async function disk(dir){try{const [s,f]=await Promise.all([fs.stat(dir),fs.statfs(dir)]);const total=f.blocks*f.bsize,free=f.bavail*f.bsize,used=(f.blocks-f.bfree)*f.bsize;return {device:s.dev,total,free,used,percent:total>0?used/total*100:null};}catch{return null;}}
async function size(file,missingZero=true){try{return (await fs.stat(file)).size;}catch(e){return e.code==='ENOENT'&&missingZero?0:null;}}
async function folder(dir,{maxEntries=2000,maxMs=300}={}){let total=0,count=0,partial=false,entries=0,newestMs=null;const start=Date.now(),queue=[dir];while(queue.length){if(entries>=maxEntries||Date.now()-start>maxMs){partial=true;break;}const current=queue.shift();let rows;try{rows=await fs.readdir(current,{withFileTypes:true});}catch(e){if(e.code==='ENOENT'&&!entries)return {bytes:0,count:0,partial:false,newestMs:null};partial=true;continue;}for(const entry of rows){if(++entries>maxEntries||Date.now()-start>maxMs){partial=true;break;}const file=path.join(current,entry.name);if(entry.isSymbolicLink())continue;if(entry.isDirectory())queue.push(file);else if(entry.isFile()){try{const stat=await fs.stat(file);total+=stat.size;count++;if(Number.isFinite(stat.mtimeMs))newestMs=Math.max(newestMs||0,stat.mtimeMs);}catch{partial=true;}}}}return {bytes:total,count,partial,newestMs};}
async function containerMemory(){for(const [usedPath,limitPath]of [['/sys/fs/cgroup/memory.current','/sys/fs/cgroup/memory.max'],['/sys/fs/cgroup/memory/memory.usage_in_bytes','/sys/fs/cgroup/memory/memory.limit_in_bytes']]){try{const [u,l]=await Promise.all([fs.readFile(usedPath,'utf8'),fs.readFile(limitPath,'utf8')]);const used=Number(u.trim()),limit=Number(l.trim());if(Number.isFinite(used)&&Number.isFinite(limit)&&limit>0&&limit<Number.MAX_SAFE_INTEGER)return {used,limit,percent:used/limit*100};}catch{}}return null;}
function warningList(s,now=Date.now()){const warnings=[];const check=(label,d)=>{if(Number.isFinite(d?.percent)&&d.percent>=90)warnings.push(label+' kritis '+d.percent.toFixed(1)+'%');else if(Number.isFinite(d?.percent)&&d.percent>=80)warnings.push(label+' tinggi '+d.percent.toFixed(1)+'%');};check('Disk aplikasi',s?.app);if(!s?.sameDisk)check('Disk database',s?.data);if(Number.isFinite(s?.memory?.percent)&&s.memory.percent>=90)warnings.push('RAM container kritis '+s.memory.percent.toFixed(1)+'%');else if(Number.isFinite(s?.memory?.percent)&&s.memory.percent>=80)warnings.push('RAM container tinggi '+s.memory.percent.toFixed(1)+'%');if(Number.isFinite(s?.database)&&Number.isFinite(s?.wal)&&s.database>0&&s.wal>Math.max(50*1024*1024,s.database*2))warnings.push('WAL SQLite membesar');if(!s?.backups?.count)warnings.push('Backup belum ditemukan');else if(Number.isFinite(s?.backups?.newestMs)&&now-s.backups.newestMs>36*60*60*1000)warnings.push('Backup terakhir lebih dari 36 jam');if(s?.backups?.partial)warnings.push('Pemeriksaan folder backup hanya sebagian');return warnings;}
function createStorageHealth({databasePath,backupDir,volumePath,appDir=process.cwd(),now=Date.now}){let cached=null,stamp=0,pending=null;return async()=>{if(cached&&now()-stamp<15000)return cached;if(pending)return pending;pending=(async()=>{const dbFile=path.resolve(databasePath),dir=path.dirname(dbFile);const [app,data,main,wal,shm,backups,memory]=await Promise.all([disk(appDir),disk(volumePath||dir),size(dbFile,false),size(dbFile+'-wal'),size(dbFile+'-shm'),folder(backupDir||path.join(dir,'backups')),containerMemory()]);const m=process.memoryUsage();const result={app,data,sameDisk:!!app&&!!data&&app.device===data.device,database:main,wal,shm,backups,memory,heapUsed:m.heapUsed,heapTotal:m.heapTotal};result.warnings=warningList(result,now());cached=result;stamp=now();return result;})().finally(()=>{pending=null;});return pending;};}
function age(ms){if(!Number.isFinite(ms))return 'Belum tersedia';const d=Math.max(0,Date.now()-ms),h=Math.floor(d/3600000),m=Math.floor((d%3600000)/60000);return h?h+'j '+m+'m lalu':m+'m lalu';}
function storageText(s){if(!s)return '\nStorage: Belum tersedia';const describe=d=>d?bytes(d.used)+' terpakai / '+bytes(d.total)+' • tersedia '+bytes(d.free)+(Number.isFinite(d.percent)?' ('+d.percent.toFixed(1)+'% terpakai)':''):'Belum tersedia';let out='\n\n**💾 Penyimpanan & Resource**\nDisk aplikasi: '+describe(s.app);if(!s.sameDisk)out+='\nDisk database / volume: '+describe(s.data);else out+='\nDatabase memakai disk yang sama.';out+='\nDatabase SQLite: '+bytes(s.database)+'\nWAL: '+bytes(s.wal)+' • SHM: '+bytes(s.shm)+'\nBackup: '+bytes(s.backups?.bytes)+' • '+(s.backups?.count??'-')+' file'+(s.backups?.partial?' (hasil sebagian)':'')+' • terbaru '+age(s.backups?.newestMs)+'\nHeap Node.js: '+bytes(s.heapUsed)+' / '+bytes(s.heapTotal);out+='\nRAM container: '+(s.memory?bytes(s.memory.used)+' / batas '+bytes(s.memory.limit)+(Number.isFinite(s.memory.percent)?' ('+s.memory.percent.toFixed(1)+'%)':''):'Batas tidak tersedia');const warnings=Array.isArray(s.warnings)?s.warnings:warningList(s);out+='\nStatus resource: '+(warnings.length?'⚠️ '+warnings.join(' • '):'✅ Normal');out+='\nAngka disk mengikuti filesystem runtime; bukan kuota paket Railway. Statistik storage disegarkan maksimal setiap 15 detik.';return out;}
module.exports={createStorageHealth,storageText,bytes,folder,warningList};
